//! Bake the React dashboard (`web/dist`) into the gateway binary using
//! plain `include_bytes!`, no embedding crate required.
//!
//! Walks the dist tree, writes a placeholder `index.html` if the
//! frontend wasn't built, then emits `$OUT_DIR/webui_assets.rs` with
//! one `match` arm per asset. `api::webui` pulls it in via `include!`.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let dist = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("gateway crate lives under <workspace>/crates/gateway")
        .join("web/dist");
    let index = dist.join("index.html");

    if !index.exists() {
        fs::create_dir_all(&dist).expect("create dist directory");
        fs::write(
            &index,
            concat!(
                "<!doctype html><html><head><meta charset=\"utf-8\">",
                "<title>Aura WebUI</title></head><body style=\"font-family:monospace;padding:2rem\">",
                "<h1>Aura WebUI not built</h1>",
                "<p>Run <code>npm ci &amp;&amp; npm run build</code> in <code>web/</code> to embed the dashboard.</p>",
                "</body></html>",
            ),
        )
        .expect("write stub index.html");
    }

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let generated = out_dir.join("webui_assets.rs");
    let mut out = fs::File::create(&generated).expect("create generated assets file");
    writeln!(out, "// @generated by build.rs — do not edit.").expect("write header");
    writeln!(
        out,
        "pub(super) fn lookup(path: &str) -> Option<(&'static [u8], &'static str)> {{",
    )
    .expect("write fn header");
    writeln!(out, "    match path {{").expect("write match open");
    for (rel, abs) in &files {
        let mime = mime_for(rel);
        writeln!(
            out,
            "        {rel:?} => Some((include_bytes!({abs:?}), {mime:?})),",
        )
        .expect("write arm");
    }
    writeln!(out, "        _ => None,").expect("write wildcard arm");
    writeln!(out, "    }}").expect("write match close");
    writeln!(out, "}}").expect("write fn close");

    println!("cargo:rerun-if-changed={}", dist.display());
}

fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(reader) = fs::read_dir(dir) else { return };
    for entry in reader.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(base, &path, out);
        } else if let Ok(rel) = path.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), path));
        }
    }
}

fn mime_for(path: &str) -> &'static str {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
