//! Bake the React dashboard and the in-tree channel sidecars into the
//! gateway binary.
//!
//! Two independent pipelines share this file:
//!
//! * **WebUI** — watches the relevant `web/` sources, reruns
//!   `pnpm --filter aura-web build` when those inputs change, then
//!   zstd-compresses each emitted `web/dist` asset and writes
//!   `$OUT_DIR/webui_assets.rs` with one compressed `include_bytes!`
//!   arm per asset. The runtime lazily decompresses the table on first
//!   request.
//! * **Sidecars** — fetches the pinned `bun` release (version in
//!   `.bun-version` at the repo root), uses it to bundle each
//!   `channel-src/*` package into a single JS blob, zstd-compresses
//!   both the runtime and each bundle, and emits
//!   `$OUT_DIR/sidecar_assets.rs` that the gateway's `sidecar` module
//!   consumes.
//!
//! The sidecar pipeline degrades gracefully: if the download fails,
//! node_modules aren't populated, or bun chokes on a bundle, we emit an
//! assets file with empty slices and print `cargo:warning=…`. The
//! gateway supervisor then skips spawning sidecars and logs a
//! one-liner — `cargo build` itself never fails because of sidecar
//! packaging trouble.

use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

use sha2::Digest;

fn main() {
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let ws_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("gateway crate lives under <workspace>/crates/gateway")
        .to_path_buf();

    embed_webui(&ws_root);
    embed_sidecars(&ws_root);
}

// ---------------------------------------------------------------------
// WebUI
// ---------------------------------------------------------------------

fn embed_webui(ws_root: &Path) {
    let web_root = ws_root.join("web");
    let dist = web_root.join("dist");
    let index = dist.join("index.html");
    let generated_schema = web_root.join("src/api/schema.d.ts");
    let webui_cache_dir = ws_root.join("target").join("webui-cache");

    let source_fingerprint = match webui_source_fingerprint(ws_root, &web_root) {
        Ok(fingerprint) => Some(fingerprint),
        Err(e) => {
            println!("cargo:warning=hash webui inputs failed ({e}); rebuilding webui");
            None
        }
    };

    let mut should_build = !index.exists() || !generated_schema.exists();
    if let Some(fingerprint) = source_fingerprint.as_deref() {
        should_build |= webui_build_required(&webui_cache_dir, fingerprint, &index);
    } else {
        should_build = true;
    }

    if should_build {
        match build_webui(ws_root) {
            Ok(()) => {
                if let Some(fingerprint) = source_fingerprint.as_deref()
                    && let Err(e) = write_webui_build_stamp(&webui_cache_dir, fingerprint)
                {
                    println!("cargo:warning=write webui build stamp failed: {e}");
                }
            }
            Err(e) => {
                println!(
                    "cargo:warning=webui build failed ({e}); using existing dist or placeholder"
                );
            }
        }
    }

    if !index.exists() {
        fs::create_dir_all(&dist).expect("create dist directory");
        fs::write(
            &index,
            concat!(
                "<!doctype html><html><head><meta charset=\"utf-8\">",
                "<title>Aura WebUI</title></head><body style=\"font-family:monospace;padding:2rem\">",
                "<h1>Aura WebUI not built</h1>",
                "<p>Run <code>pnpm install &amp;&amp; pnpm --filter aura-web build</code> to embed the dashboard.</p>",
                "</body></html>",
            ),
        )
        .expect("write stub index.html");
    }

    let mut files = Vec::new();
    collect_assets(&dist, &dist, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let generated = out_dir.join("webui_assets.rs");
    let mut out = fs::File::create(&generated).expect("create generated assets file");
    writeln!(out, "// @generated by build.rs — do not edit.").expect("write header");
    writeln!(
        out,
        "pub(super) struct WebAsset {{ \
         pub path: &'static str, \
         pub mime: &'static str, \
         pub content_zst: &'static [u8] \
         }}",
    )
    .expect("write struct");
    writeln!(out, "pub(super) const ASSETS: &[WebAsset] = &[").expect("write array open");
    for (idx, (rel, abs)) in files.iter().enumerate() {
        let mime = mime_for(rel);
        let zst_path = out_dir.join(web_asset_zst_name(idx, rel));
        compress_file(abs, &zst_path).expect("compress web asset");
        writeln!(
            out,
            "    WebAsset {{ path: {rel:?}, mime: {mime:?}, content_zst: include_bytes!({zst_path:?}) }},",
        )
        .expect("write asset");
    }
    writeln!(out, "];").expect("write array close");

    emit_rerun_if_changed(&dist);
}

fn collect_assets(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(reader) = fs::read_dir(dir) else {
        return;
    };
    for entry in reader.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_assets(base, &path, out);
        } else if let Ok(rel) = path.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), path));
        }
    }
}

fn mime_for(path: &str) -> &'static str {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn web_asset_zst_name(index: usize, rel: &str) -> String {
    let mut sanitized = String::with_capacity(rel.len());
    for ch in rel.chars() {
        if ch.is_ascii_alphanumeric() {
            sanitized.push(ch);
        } else {
            sanitized.push('_');
        }
    }
    format!("webui-{index:04}-{sanitized}.zst")
}

fn webui_source_fingerprint(ws_root: &Path, web_root: &Path) -> Result<String, String> {
    let input_roots = webui_input_roots(ws_root, web_root);
    for path in &input_roots {
        emit_rerun_if_changed_filtered(path, &|candidate| {
            is_webui_generated_source(web_root, candidate)
        });
    }

    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    for path in &input_roots {
        hash_path_state_filtered(&mut hasher, ws_root, path, &|candidate| {
            is_webui_generated_source(web_root, candidate)
        })?;
    }
    Ok(hex_short(&hasher.finalize(), 64))
}

fn webui_input_roots(ws_root: &Path, web_root: &Path) -> Vec<PathBuf> {
    let mut paths = vec![
        ws_root.join("pnpm-lock.yaml"),
        ws_root.join("pnpm-workspace.yaml"),
        ws_root.join("docs/openapi.json"),
        web_root.join("index.html"),
        web_root.join("package.json"),
        web_root.join("tsconfig.json"),
        web_root.join("tsconfig.app.json"),
        web_root.join("tsconfig.node.json"),
        web_root.join("vite.config.ts"),
        web_root.join("src"),
        web_root.join("public"),
    ];
    paths.sort();
    paths.dedup();
    paths
}

fn is_webui_generated_source(web_root: &Path, path: &Path) -> bool {
    path == web_root.join("src/api/schema.d.ts")
}

fn webui_build_required(cache_dir: &Path, fingerprint: &str, index: &Path) -> bool {
    if !index.exists() {
        return true;
    }
    let stamp = cache_dir.join("source-fingerprint.txt");
    let Ok(raw) = fs::read_to_string(&stamp) else {
        return true;
    };
    raw.trim() != fingerprint
}

fn write_webui_build_stamp(cache_dir: &Path, fingerprint: &str) -> Result<(), String> {
    fs::create_dir_all(cache_dir).map_err(|e| format!("mkdir {}: {e}", cache_dir.display()))?;
    let stamp = cache_dir.join("source-fingerprint.txt");
    fs::write(&stamp, format!("{fingerprint}\n"))
        .map_err(|e| format!("write {}: {e}", stamp.display()))
}

fn build_webui(ws_root: &Path) -> Result<(), String> {
    let output = Command::new("pnpm")
        .arg("--filter")
        .arg("aura-web")
        .arg("build")
        .current_dir(ws_root)
        .output()
        .map_err(|e| format!("spawn pnpm: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "pnpm build exited {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        ));
    }
    Ok(())
}

fn emit_rerun_if_changed_filtered<F>(path: &Path, skip: &F)
where
    F: Fn(&Path) -> bool,
{
    if !path.exists() || skip(path) {
        return;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    if !path.is_dir() {
        return;
    }
    for entry in list_dir_entries(path) {
        emit_rerun_if_changed_filtered(&entry, skip);
    }
}

fn hash_path_state_filtered<F>(
    hasher: &mut sha2::Sha256,
    ws_root: &Path,
    path: &Path,
    skip: &F,
) -> Result<(), String>
where
    F: Fn(&Path) -> bool,
{
    if skip(path) {
        return Ok(());
    }
    let rel = path
        .strip_prefix(ws_root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/");
    hasher.update(rel.as_bytes());
    hasher.update([0]);
    if !path.exists() {
        hasher.update(b"missing");
        hasher.update([0]);
        return Ok(());
    }
    if path.is_dir() {
        hasher.update(b"dir");
        hasher.update([0]);
        for entry in list_dir_entries(path) {
            hash_path_state_filtered(hasher, ws_root, &entry, skip)?;
        }
        return Ok(());
    }
    hasher.update(b"file");
    hasher.update([0]);
    let bytes = fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    hasher.update(&bytes);
    hasher.update([0]);
    Ok(())
}

fn list_dir_entries(dir: &Path) -> Vec<PathBuf> {
    let mut entries = Vec::new();
    let Ok(reader) = fs::read_dir(dir) else {
        return entries;
    };
    for entry in reader.flatten() {
        entries.push(entry.path());
    }
    entries.sort();
    entries
}

// ---------------------------------------------------------------------
// Sidecar embedding
// ---------------------------------------------------------------------

/// zstd level. Level 19 is the upper end of the "reasonable" range —
/// ~10% smaller output than 3 at a ~10x build-time cost. Given the
/// output is cached for unchanged sidecar inputs and the binary ships
/// to every user, paying the build-time cost is the right tradeoff.
const ZSTD_LEVEL: i32 = 19;

fn embed_sidecars(ws_root: &Path) {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let generated = out_dir.join("sidecar_assets.rs");
    let strict = sidecars_required();

    let bun_version = match read_bun_version(ws_root) {
        Ok(v) => v,
        Err(e) => {
            sidecar_failure(strict, &e);
            write_empty_sidecar_assets(&generated, "unknown", "unknown");
            return;
        }
    };

    emit_rerun_if_changed(&ws_root.join(".bun-version"));
    println!("cargo:rerun-if-env-changed={STRICT_SIDECARS_ENV}");

    // `host_target` is the bun build needs to actually exec on this
    // machine to bundle TS → JS. `runtime_target` is the bun we ship
    // inside the binary so it can exec on the final aura host.
    // Conflating the two silently broke `cargo build --target ≠ host`
    // (host couldn't exec the target binary, bundling failed, build
    // succeeded with empty sidecars).
    let Some(host_target) = detect_host_bun_target() else {
        let msg = format!(
            "unsupported build host for bun (os={}, arch={}); sidecars disabled",
            std::env::consts::OS,
            std::env::consts::ARCH,
        );
        sidecar_failure(strict, &msg);
        write_empty_sidecar_assets(&generated, &bun_version, "unsupported-host");
        return;
    };
    let Some(runtime_target) = detect_runtime_bun_target() else {
        let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
        let arch = std::env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
        let msg =
            format!("unsupported runtime target for bun (os={os}, arch={arch}); sidecars disabled");
        sidecar_failure(strict, &msg);
        write_empty_sidecar_assets(&generated, &bun_version, "unsupported-target");
        return;
    };

    // `channel-src/` holds one directory per in-tree sidecar.
    let sidecars_dir = ws_root.join("channel-src");
    let sidecar_dirs = list_sidecar_dirs(&sidecars_dir);
    let cache_root = ws_root.join("target").join("sidecar-cache");
    let input_fingerprint = match sidecar_input_fingerprint(
        ws_root,
        &bun_version,
        &host_target,
        &runtime_target,
        &sidecar_dirs,
    ) {
        Ok(fingerprint) => fingerprint,
        Err(e) => {
            println!("cargo:warning=hash sidecar inputs failed ({e}); rebuilding sidecars");
            String::new()
        }
    };
    let cache_dir = cache_root.join(if input_fingerprint.is_empty() {
        "adhoc".to_string()
    } else {
        input_fingerprint.clone()
    });

    if !input_fingerprint.is_empty() {
        match load_sidecar_cache(&cache_dir) {
            Ok(Some(cache)) => {
                emit_sidecar_assets(
                    &generated,
                    &bun_version,
                    &runtime_target,
                    Some(cache.bun_zst.as_path()),
                    &cache.sidecars,
                );
                return;
            }
            Ok(None) => {}
            Err(e) => {
                println!("cargo:warning=read sidecar cache failed ({e}); rebuilding sidecars");
            }
        }
    }

    let host_bun = match ensure_bun(ws_root, &bun_version, &host_target) {
        Ok(p) => p,
        Err(e) => {
            let msg = format!("host bun download failed ({e}); sidecars disabled");
            sidecar_failure(strict, &msg);
            write_empty_sidecar_assets(&generated, &bun_version, &runtime_target);
            return;
        }
    };
    let runtime_bun = if runtime_target == host_target {
        host_bun.clone()
    } else {
        match ensure_bun(ws_root, &bun_version, &runtime_target) {
            Ok(p) => p,
            Err(e) => {
                let msg = format!(
                    "runtime bun download failed for {runtime_target} ({e}); sidecars disabled"
                );
                sidecar_failure(strict, &msg);
                write_empty_sidecar_assets(&generated, &bun_version, &runtime_target);
                return;
            }
        }
    };

    if let Err(e) = fs::create_dir_all(&cache_dir) {
        let msg = format!(
            "create sidecar cache dir {} failed: {e}",
            cache_dir.display()
        );
        sidecar_failure(strict, &msg);
        write_empty_sidecar_assets(&generated, &bun_version, &runtime_target);
        return;
    }

    let mut entries: Vec<(String, PathBuf, String)> = Vec::new();
    let mut bundling_failures = 0usize;
    for dir in &sidecar_dirs {
        let name = dir.file_name().and_then(|s| s.to_str()).unwrap_or("?");
        let entry_ts = dir.join("src/index.ts");
        if !entry_ts.exists() {
            println!("cargo:warning=sidecar '{name}' has no src/index.ts; skipping",);
            continue;
        }
        let bundle_path = cache_dir.join(format!("{name}.js"));
        match bundle_with_bun(&host_bun, &entry_ts, &bundle_path) {
            Ok(()) => {
                let hash = sha256_hex(&bundle_path);
                entries.push((name.to_string(), bundle_path, hash));
            }
            Err(e) => {
                bundling_failures += 1;
                let msg = format!("bundling sidecar '{name}' failed: {e}");
                sidecar_failure(strict, &msg);
            }
        }
    }
    if strict && bundling_failures > 0 {
        // sidecar_failure has already paniced above, but defensively
        // bail before we ship a partial set.
        panic!("{STRICT_SIDECARS_ENV} is set but {bundling_failures} sidecar(s) failed to bundle",);
    }

    // Compress bun + each bundle into the content-addressed sidecar
    // cache. The generated Rust then points `include_bytes!` at those
    // absolute paths.
    let bun_zst = cache_dir.join("bun.zst");
    if let Err(e) = compress_file(&runtime_bun, &bun_zst) {
        let msg = format!("compress bun runtime failed: {e}");
        sidecar_failure(strict, &msg);
        write_empty_sidecar_assets(&generated, &bun_version, &runtime_target);
        return;
    }

    let mut emitted: Vec<(String, PathBuf, String)> = Vec::new(); // (name, zst_path, hash)
    for (name, bundle, hash) in &entries {
        let zst_path = cache_dir.join(format!("{name}.js.zst"));
        if let Err(e) = compress_file(bundle, &zst_path) {
            let msg = format!("compress sidecar '{name}' failed: {e}");
            sidecar_failure(strict, &msg);
            continue;
        }
        emitted.push((name.clone(), zst_path, hash.clone()));
    }

    if emitted.len() == entries.len()
        && let Err(e) = write_sidecar_cache_manifest(&cache_dir, &emitted)
    {
        println!("cargo:warning=write sidecar cache manifest failed: {e}");
    }

    emit_sidecar_assets(
        &generated,
        &bun_version,
        &runtime_target,
        Some(&bun_zst),
        &emitted,
    );
}

/// Opt-in CI/release gate: when set to `1`/`true`, any sidecar
/// packaging failure becomes a hard build error instead of a
/// `cargo:warning` + empty-asset degrade. The gateway binary boots fine
/// without sidecars during local backend hacking, but a release build
/// with no embedded channels is almost always a packaging mistake.
const STRICT_SIDECARS_ENV: &str = "AURA_REQUIRE_SIDECARS";

fn sidecars_required() -> bool {
    matches!(
        std::env::var(STRICT_SIDECARS_ENV).ok().as_deref(),
        Some("1") | Some("true") | Some("TRUE") | Some("yes")
    )
}

fn sidecar_failure(strict: bool, msg: &str) {
    if strict {
        panic!("{STRICT_SIDECARS_ENV}=1 and sidecar packaging failed: {msg}");
    }
    println!("cargo:warning={msg}");
}

fn read_bun_version(ws_root: &Path) -> Result<String, String> {
    let path = ws_root.join(".bun-version");
    let raw = fs::read_to_string(&path).map_err(|e| {
        format!(
            "read {}: {e}; sidecars disabled (create the file with a bun version number)",
            path.display()
        )
    })?;
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return Err(format!("{} is empty", path.display()));
    }
    // Defend against paste errors ("v1.2.18\n" → "1.2.18").
    Ok(trimmed.trim_start_matches('v').to_owned())
}

/// bun release naming for the **host** that runs `build.rs` — i.e.
/// the bun we'll exec to bundle TS → JS at compile time.
fn detect_host_bun_target() -> Option<String> {
    bun_target(std::env::consts::OS, std::env::consts::ARCH)
}

/// bun release naming for the cargo **target** triple — i.e. the bun
/// we compress into the binary so it can exec on the final aura host.
/// Different from the host when cross-compiling.
fn detect_runtime_bun_target() -> Option<String> {
    let os = std::env::var("CARGO_CFG_TARGET_OS").ok()?;
    let arch = std::env::var("CARGO_CFG_TARGET_ARCH").ok()?;
    bun_target(&os, &arch)
}

fn bun_target(os: &str, arch: &str) -> Option<String> {
    match (os, arch) {
        ("linux", "x86_64") => Some("linux-x64".into()),
        ("linux", "aarch64") => Some("linux-aarch64".into()),
        ("macos", "x86_64") => Some("darwin-x64".into()),
        ("macos", "aarch64") => Some("darwin-aarch64".into()),
        _ => None,
    }
}

/// Download + cache the pinned bun release. Cache path sits under
/// `target/bun-cache/` so a `cargo clean` wipes it, but any other
/// rebuild reuses the extracted binary. Returns a path to the
/// executable-bit-set `bun` on disk. Verifies the downloaded zip's
/// sha256 against `.bun-shasums` — mismatch is a hard fail;
/// missing entry downgrades to an unverified download with a loud
/// cargo:warning.
fn ensure_bun(ws_root: &Path, version: &str, target: &str) -> Result<PathBuf, String> {
    let cache_dir = ws_root.join("target").join("bun-cache");
    fs::create_dir_all(&cache_dir).map_err(|e| format!("mkdir cache: {e}"))?;
    let dest = cache_dir.join(format!("bun-{version}-{target}"));
    if dest.exists() {
        // Cache hit: trust. The shasum check ran at the original
        // download, and `target/` is under the user's build tree.
        return Ok(dest);
    }

    let expected_sha = load_pinned_sha(ws_root, target);
    println!(
        "cargo:rerun-if-changed={}",
        ws_root.join(".bun-shasums").display(),
    );

    let url =
        format!("https://github.com/oven-sh/bun/releases/download/bun-v{version}/bun-{target}.zip");
    println!("cargo:warning=downloading bun {version} for {target}...");
    let resp = ureq::get(&url)
        .call()
        .map_err(|e| format!("GET {url}: {e}"))?;

    let mut zip_bytes = Vec::new();
    resp.into_reader()
        .read_to_end(&mut zip_bytes)
        .map_err(|e| format!("read zip body: {e}"))?;

    let got_sha = sha256_hex_full(&zip_bytes);
    match expected_sha {
        Some(expected) if expected == got_sha => {}
        Some(expected) => {
            // Hard fail, not a graceful-degrade condition. A sha
            // mismatch means either `.bun-shasums` is wrong or the
            // release bytes changed underneath us — in either case
            // we must not silently ship an unpinned binary.
            panic!(
                "sha256 mismatch for bun-{target}.zip:\n  expected {expected}\n  got      {got_sha}\n\
                 The pinned release was replaced or the download was tampered with. Refusing to build.\n\
                 If the version bump is intentional, update .bun-shasums and commit.",
            );
        }
        None => {
            println!(
                "cargo:warning=no pinned sha256 for bun-{target}.zip in .bun-shasums; \
                 proceeding UNVERIFIED (computed {got_sha}). \
                 Add this line to .bun-shasums to pin:",
            );
            println!("cargo:warning={got_sha}  bun-{target}.zip");
        }
    }

    // Upstream zip layout: `bun-{target}/bun`.
    let reader = std::io::Cursor::new(&zip_bytes);
    let mut archive = zip::ZipArchive::new(reader).map_err(|e| format!("open zip: {e}"))?;
    let inner_name = format!("bun-{target}/bun");
    let mut entry = archive
        .by_name(&inner_name)
        .map_err(|e| format!("{inner_name} not in zip: {e}"))?;

    let tmp = dest.with_extension("part");
    let mut out = fs::File::create(&tmp).map_err(|e| format!("create {}: {e}", tmp.display()))?;
    std::io::copy(&mut entry, &mut out).map_err(|e| format!("extract bun: {e}"))?;
    drop(entry);
    drop(out);

    // Set +x before the rename so the final name is never a
    // non-executable file that a concurrent build would find first.
    set_executable(&tmp)?;
    fs::rename(&tmp, &dest).map_err(|e| format!("rename extracted bun: {e}"))?;
    Ok(dest)
}

/// Parse `.bun-shasums` (SHASUMS256-style: `<hex> <2sp> <filename>`)
/// and pluck the entry matching `bun-{target}.zip`. Returns `None`
/// on file-not-found or no-matching-line — the caller downgrades to
/// an unverified download with a warning.
fn load_pinned_sha(ws_root: &Path, target: &str) -> Option<String> {
    let raw = fs::read_to_string(ws_root.join(".bun-shasums")).ok()?;
    let needle = format!("bun-{target}.zip");
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Expected: "<64-hex>  <filename>". Accept any whitespace
        // between the two so hand-edited files don't trip on tabs.
        let mut parts = line.split_whitespace();
        let hex = parts.next()?;
        let name = parts.next()?;
        if name == needle && hex.len() == 64 && hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Some(hex.to_ascii_lowercase());
        }
    }
    None
}

fn sha256_hex_full(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(64);
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for b in digest {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

fn set_executable(path: &Path) -> Result<(), String> {
    use std::os::unix::fs::PermissionsExt;
    let mut perms = fs::metadata(path)
        .map_err(|e| format!("stat {}: {e}", path.display()))?
        .permissions();
    perms.set_mode(0o755);
    fs::set_permissions(path, perms).map_err(|e| format!("chmod: {e}"))
}

fn list_sidecar_dirs(root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    let Ok(reader) = fs::read_dir(root) else {
        return dirs;
    };
    for entry in reader.flatten() {
        let p = entry.path();
        if p.is_dir() {
            dirs.push(p);
        }
    }
    dirs.sort();
    dirs
}

fn sidecar_input_fingerprint(
    ws_root: &Path,
    bun_version: &str,
    host_target: &str,
    runtime_target: &str,
    sidecar_dirs: &[PathBuf],
) -> Result<String, String> {
    let input_roots = sidecar_input_roots(ws_root, sidecar_dirs);
    println!(
        "cargo:rerun-if-changed={}",
        ws_root.join("channel-src").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        ws_root.join("sdks/channel-ts").display()
    );
    for dir in sidecar_dirs {
        println!("cargo:rerun-if-changed={}", dir.display());
    }
    for path in &input_roots {
        emit_rerun_if_changed(path);
    }

    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(bun_version.as_bytes());
    hasher.update([0]);
    hasher.update(host_target.as_bytes());
    hasher.update([0]);
    hasher.update(runtime_target.as_bytes());
    hasher.update([0]);
    for path in &input_roots {
        hash_path_state(&mut hasher, ws_root, path)?;
    }
    Ok(hex_short(&hasher.finalize(), 64))
}

fn sidecar_input_roots(ws_root: &Path, sidecar_dirs: &[PathBuf]) -> Vec<PathBuf> {
    let mut paths = vec![
        ws_root.join("pnpm-lock.yaml"),
        ws_root.join("pnpm-workspace.yaml"),
        ws_root.join("sdks/channel-ts/dist"),
        ws_root.join("sdks/channel-ts/package.json"),
        ws_root.join("sdks/channel-ts/tsconfig.json"),
    ];
    for dir in sidecar_dirs {
        paths.push(dir.join("src"));
        paths.push(dir.join("package.json"));
        paths.push(dir.join("tsconfig.json"));
        paths.push(dir.join("bunfig.toml"));
    }
    paths.sort();
    paths.dedup();
    paths
}

fn emit_rerun_if_changed(path: &Path) {
    if !path.exists() {
        return;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    if !path.is_dir() {
        return;
    }
    let mut files = Vec::new();
    collect_files(path, &mut files);
    for file in files {
        println!("cargo:rerun-if-changed={}", file.display());
    }
}

fn collect_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(reader) = fs::read_dir(dir) else {
        return;
    };
    for entry in reader.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, out);
        } else {
            out.push(path);
        }
    }
    out.sort();
}

fn hash_path_state(hasher: &mut sha2::Sha256, ws_root: &Path, path: &Path) -> Result<(), String> {
    let rel = path
        .strip_prefix(ws_root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/");
    hasher.update(rel.as_bytes());
    hasher.update([0]);
    if !path.exists() {
        hasher.update(b"missing");
        hasher.update([0]);
        return Ok(());
    }
    if path.is_dir() {
        hasher.update(b"dir");
        hasher.update([0]);
        let mut files = Vec::new();
        collect_files(path, &mut files);
        for file in files {
            hash_path_state(hasher, ws_root, &file)?;
        }
        return Ok(());
    }
    hasher.update(b"file");
    hasher.update([0]);
    let bytes = fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    hasher.update(&bytes);
    hasher.update([0]);
    Ok(())
}

/// `bun build <entry> --target=bun --minify --outfile=<out>`.
///
/// `--target=bun` is the leaner option (~60 KB smaller bundle after
/// zstd) because bun substitutes its own polyfill for the `ws` npm
/// package and the polyfill is WHATWG-`WebSocket`-backed. The
/// channel SDK is careful to stay within WHATWG — it puts the auth
/// token in the URL query (`?token=…`) rather than a custom HTTP
/// header, since the standard `WebSocket` constructor can't set
/// request headers. If the SDK ever needs to send headers again,
/// flip this back to `--target=node` so the real `ws` library is
/// inlined.
fn bundle_with_bun(bun: &Path, entry: &Path, out_file: &Path) -> Result<(), String> {
    let output = Command::new(bun)
        .arg("build")
        .arg(entry)
        .arg("--target=bun")
        .arg("--minify")
        .arg("--outfile")
        .arg(out_file)
        .output()
        .map_err(|e| format!("spawn bun: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "bun build exited {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        ));
    }
    Ok(())
}

fn compress_file(src: &Path, dst: &Path) -> Result<(), String> {
    let data = fs::read(src).map_err(|e| format!("read {}: {e}", src.display()))?;
    let compressed = zstd::bulk::compress(&data, ZSTD_LEVEL)
        .map_err(|e| format!("zstd compress {}: {e}", src.display()))?;
    fs::write(dst, &compressed).map_err(|e| format!("write {}: {e}", dst.display()))
}

fn sha256_hex(path: &Path) -> String {
    use sha2::{Digest, Sha256};
    let bytes = fs::read(path).unwrap_or_default();
    let digest = Sha256::digest(&bytes);
    // 16 hex chars (8 bytes) — enough to key a cache directory without
    // bloating the filename.
    hex_short(&digest, 16)
}

fn hex_short(bytes: &[u8], len: usize) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(len);
    for b in bytes {
        if out.len() >= len {
            break;
        }
        out.push(HEX[(b >> 4) as usize] as char);
        if out.len() >= len {
            break;
        }
        out.push(HEX[(b & 0x0f) as usize] as char);
    }
    out
}

fn emit_sidecar_assets(
    generated: &Path,
    bun_version: &str,
    bun_target: &str,
    bun_zst_path: Option<&Path>,
    sidecars: &[(String, PathBuf, String)],
) {
    let mut out = fs::File::create(generated).expect("create sidecar_assets.rs");
    writeln!(out, "// @generated by build.rs — do not edit.").unwrap();
    writeln!(out, "pub(crate) const BUN_VERSION: &str = {bun_version:?};",).unwrap();
    writeln!(out, "pub(crate) const BUN_TARGET: &str = {bun_target:?};").unwrap();
    if sidecars.is_empty() {
        writeln!(out, "pub(crate) const BUN_RUNTIME_ZST: &[u8] = &[];").unwrap();
    } else if let Some(path) = bun_zst_path {
        writeln!(
            out,
            "pub(crate) const BUN_RUNTIME_ZST: &[u8] = include_bytes!({path:?});",
        )
        .unwrap();
    } else {
        writeln!(out, "pub(crate) const BUN_RUNTIME_ZST: &[u8] = &[];").unwrap();
    }
    writeln!(
        out,
        "pub(crate) struct SidecarAsset {{ \
         pub channel_type: &'static str, \
         pub bundle_zst: &'static [u8], \
         pub content_hash: &'static str \
         }}",
    )
    .unwrap();
    writeln!(out, "pub(crate) const SIDECARS: &[SidecarAsset] = &[").unwrap();
    for (name, zst_path, hash) in sidecars {
        writeln!(
            out,
            "    SidecarAsset {{ channel_type: {name:?}, bundle_zst: include_bytes!({zst_path:?}), content_hash: {hash:?} }},",
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn write_empty_sidecar_assets(generated: &Path, bun_version: &str, bun_target: &str) {
    emit_sidecar_assets(generated, bun_version, bun_target, None, &[]);
}

struct SidecarCache {
    bun_zst: PathBuf,
    sidecars: Vec<(String, PathBuf, String)>,
}

fn load_sidecar_cache(cache_dir: &Path) -> Result<Option<SidecarCache>, String> {
    let manifest = cache_dir.join("manifest.tsv");
    if !manifest.exists() {
        return Ok(None);
    }
    let raw =
        fs::read_to_string(&manifest).map_err(|e| format!("read {}: {e}", manifest.display()))?;
    let bun_zst = cache_dir.join("bun.zst");
    if !bun_zst.exists() {
        return Ok(None);
    }

    let mut sidecars = Vec::new();
    for line in raw.lines() {
        let mut parts = line.split('\t');
        let kind = parts.next().unwrap_or_default();
        if kind != "sidecar" {
            continue;
        }
        let name = parts.next().unwrap_or_default();
        let hash = parts.next().unwrap_or_default();
        if name.is_empty() || hash.is_empty() {
            return Err(format!(
                "invalid sidecar cache manifest entry in {}",
                manifest.display()
            ));
        }
        let zst_path = cache_dir.join(format!("{name}.js.zst"));
        if !zst_path.exists() {
            return Ok(None);
        }
        sidecars.push((name.to_string(), zst_path, hash.to_string()));
    }

    Ok(Some(SidecarCache { bun_zst, sidecars }))
}

fn write_sidecar_cache_manifest(
    cache_dir: &Path,
    sidecars: &[(String, PathBuf, String)],
) -> Result<(), String> {
    fs::create_dir_all(cache_dir).map_err(|e| format!("mkdir {}: {e}", cache_dir.display()))?;
    let manifest = cache_dir.join("manifest.tsv");
    let mut out = String::new();
    for (name, _path, hash) in sidecars {
        out.push_str(&format!("sidecar\t{name}\t{hash}\n"));
    }
    fs::write(&manifest, out).map_err(|e| format!("write {}: {e}", manifest.display()))
}
