/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{channel_type}/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Round-trip a diagnose self-test against the sidecar serving
         *     `:channel_type`. The request is gated by the sidecar's advertised
         *     `"diagnose"` capability — sidecars that don't claim it return
         *     HTTP 501 instead of timing out.
         */
        get: operations["diagnose_channel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put: operations["set_config"];
        post?: never;
        delete: operations["unset_config"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_cron"];
        put?: never;
        post: operations["create_cron"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cron/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_cron"];
        put?: never;
        post?: never;
        delete: operations["delete_cron"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_llm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_memory"];
        put?: never;
        post: operations["store_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_memory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_skills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Mirror of [`aura_model::ApprovedResource`]. Paths serialize as
         *     strings on the wire.
         */
        ApprovedResource: {
            /** @enum {string} */
            kind: "read_file";
            path: string;
        } | {
            /** @enum {string} */
            kind: "write_file";
            path: string;
        } | {
            host: components["schemas"]["HostPattern"];
            /** @enum {string} */
            kind: "http";
        } | {
            command: string;
            /** @enum {string} */
            kind: "exec_command";
        };
        /**
         * @description Admin-surface mirror of [`aura_model::ChannelType`]. Transparent
         *     wrapper around a snake_case string so the OpenAPI surface stays
         *     stable while the core type is open-ended (runtime-registered
         *     sidecars like `"slack"` pass through unchanged).
         */
        ChannelType: string;
        /**
         * @description `POST /v1/cron` body. Schedule format is the standard 5-field cron
         *     string accepted by [`aura_cron`].
         */
        CreateCronRequest: {
            channel?: null | components["schemas"]["ChannelType"];
            origin_session_id?: string | null;
            schedule: string;
            text: string;
            user_id: string;
        };
        /** @description Mirror of [`aura_cron::CronJob`]. */
        CronJob: {
            action: components["schemas"]["TriggerAction"];
            channel: components["schemas"]["ChannelType"];
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            last_triggered_at?: string | null;
            /** Format: date-time */
            next_trigger_at?: string | null;
            origin_session_id?: string | null;
            schedule: components["schemas"]["CronSchedule"];
            status: components["schemas"]["CronStatus"];
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        /** @description Mirror of [`aura_cron::CronSchedule`]. */
        CronSchedule: {
            expr: string;
            /** @enum {string} */
            kind: "cron";
        } | {
            /** @enum {string} */
            kind: "at";
            /** Format: date-time */
            time: string;
        };
        /**
         * @description Mirror of [`aura_cron::CronStatus`].
         * @enum {string}
         */
        CronStatus: "enabled" | "disabled";
        DiagnoseCheckEntry: {
            detail: string;
            name: string;
            /**
             * @description `"ok"` / `"warn"` / `"error"` — string-typed so third-party
             *     clients can render without a typed enum.
             */
            status: string;
        };
        /**
         * @description Uniform error envelope for every non-2xx admin response.
         *
         *     `GatewayError::into_response` already emits `{"error": "..."}`; this
         *     type just pins the shape in the spec so clients can discriminate on
         *     it rather than on status codes alone.
         */
        ErrorBody: {
            error: string;
        };
        /** @description Mirror of [`aura_model::HostPattern`]. */
        HostPattern: {
            /** @enum {string} */
            kind: "exact";
            value: string;
        } | {
            /** @enum {string} */
            kind: "wildcard";
            value: string;
        };
        /** @description Mirror of [`aura_job::Job`]. */
        Job: {
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            id: string;
            input?: Record<string, never> | null;
            kind: components["schemas"]["OperationKind"];
            output?: Record<string, never> | null;
            parent_job_id?: string | null;
            session_id: string;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
            trace_span_id?: string | null;
        };
        /**
         * @description Mirror of [`aura_job::JobStatus`].
         * @enum {string}
         */
        JobStatus: "pending" | "in_progress" | "completed" | "submitted" | "accepted" | "failed" | "stuck";
        /** @description Current LLM provider descriptor. */
        LlmInfo: {
            model_id: string;
            provider: string;
        };
        /**
         * @description Mirror of [`crate::log_buffer::LogRecord`]. Used as the item type of
         *     [`LogsResponse`].
         */
        LogEntry: {
            fields: components["schemas"]["LogField"][];
            /** Format: int64 */
            id: number;
            level: components["schemas"]["LogLevel"];
            message: string;
            /**
             * @description Tracing target that emitted the record (e.g.
             *     `aura_gateway::server`). Rendered as "source" in the UI.
             */
            target: string;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Single structured tracing field (`k=v`) captured alongside a log
         *     record. Kept as free-form strings — formatting / unquoting happens
         *     in the emitter.
         */
        LogField: {
            name: string;
            value: string;
        };
        /**
         * @description Mirror of [`crate::log_buffer::LogLevel`]. Snake-cased on the wire to
         *     match the rest of the admin surface.
         * @enum {string}
         */
        LogLevel: "error" | "warn" | "info" | "debug" | "trace";
        /**
         * @description Envelope for `GET /v1/logs`. Unlike [`ListResponse`] we expose
         *     `total` so the UI can render pagination (`Showing X of N`).
         */
        LogsResponse: {
            items: components["schemas"]["LogEntry"][];
            /**
             * @description Total number of records matching the filters — independent of
             *     `limit`/`offset`, so clients can size the pager without asking
             *     for the full list.
             */
            total: number;
        };
        MemoryCategory: {
            /** @enum {string} */
            type: "UserPreference" | "KeyFact";
        };
        /** @description Mirror of [`aura_model::MemoryEntry`]. */
        MemoryEntry: {
            category: components["schemas"]["MemoryCategory"];
            content: string;
            /** Format: date-time */
            created_at: string;
            embedding?: number[] | null;
            /** Format: date-time */
            expires_at?: string | null;
            id: string;
            /** Format: float */
            importance: number;
            /** Format: date-time */
            last_accessed: string;
            source_session_id?: string | null;
            user_id: string;
        };
        /** @description Response body for `PUT` / `DELETE /v1/config`. */
        MutateResponse: {
            path: string;
            requires_restart: boolean;
            written_to: string;
        };
        /** @description Mirror of [`aura_job::OperationKind`]. */
        OperationKind: {
            model: string;
            /** @enum {string} */
            type: "llm_call";
        } | {
            tool_name: string;
            /** @enum {string} */
            type: "tool_execution";
        } | {
            skill_name: string;
            /** @enum {string} */
            type: "skill_execution";
        } | {
            cron_job_id: string;
            /** @enum {string} */
            type: "cron_execution";
        } | {
            strategy: string;
            /** @enum {string} */
            type: "context_compression";
        } | {
            operation: string;
            /** @enum {string} */
            type: "memory_operation";
        } | {
            session_id: string;
            /** @enum {string} */
            type: "user_message_handling";
        };
        /** @description `PUT /v1/config` body. */
        SetConfigRequest: {
            path: string;
            /** @description JSON value written at `path`. Shape validated by `AuraConfig`. */
            value: Record<string, never>;
        };
        /** @description Minimal gateway health/status payload. */
        StatusResponse: {
            bind_address: string;
            jobs_in_flight: number;
            sessions: number;
            version: string;
        };
        /** @description `POST /v1/memory` body. */
        StoreMemoryRequest: {
            content: string;
            /** Format: float */
            importance?: number | null;
            user_id?: string | null;
        };
        /** @description Mirror of [`aura_cron::TriggerAction`]. */
        TriggerAction: {
            /** @enum {string} */
            kind: "prompt";
            prompt: string;
        } | {
            approved_resources: components["schemas"]["ApprovedResource"][];
            /** @enum {string} */
            kind: "tool_call";
            params: Record<string, never>;
            tool_name: string;
        };
        /** @description `DELETE /v1/config` body. */
        UnsetConfigRequest: {
            path: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            channel_type: components["schemas"]["ChannelType"];
                            status: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    diagnose_channel: {
        parameters: {
            query: {
                /** @description Per-tenant bot id */
                bot_id: string;
            };
            header?: never;
            path: {
                /** @description Sidecar channel type (e.g. `lark`) */
                channel_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Diagnose report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        bot_id: string;
                        channel_type: string;
                        checks: components["schemas"]["DiagnoseCheckEntry"][];
                    };
                };
            };
            /** @description No sidecar connected */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Sidecar lacks `diagnose` capability */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Sidecar did not reply in time */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current in-memory config. Secret fields are redacted by `AuraConfig`'s serde impl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConfigRequest"];
            };
        };
        responses: {
            /** @description Config updated on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Invalid path or value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unset_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsetConfigRequest"];
            };
        };
        responses: {
            /** @description Config entry removed on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Invalid path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_cron: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All cron jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            action: components["schemas"]["TriggerAction"];
                            channel: components["schemas"]["ChannelType"];
                            /** Format: date-time */
                            created_at: string;
                            id: string;
                            /** Format: date-time */
                            last_triggered_at?: string | null;
                            /** Format: date-time */
                            next_trigger_at?: string | null;
                            origin_session_id?: string | null;
                            schedule: components["schemas"]["CronSchedule"];
                            status: components["schemas"]["CronStatus"];
                            /** Format: date-time */
                            updated_at: string;
                            user_id: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Scheduler error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_cron: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCronRequest"];
            };
        };
        responses: {
            /** @description Created cron job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJob"];
                };
            };
            /** @description Invalid schedule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cron: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cron job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cron job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cron: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cron job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cron job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Scheduler error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All jobs currently tracked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: date-time */
                            completed_at?: string | null;
                            /** Format: date-time */
                            created_at: string;
                            error?: string | null;
                            id: string;
                            input?: Record<string, never> | null;
                            kind: components["schemas"]["OperationKind"];
                            output?: Record<string, never> | null;
                            parent_job_id?: string | null;
                            session_id: string;
                            /** Format: date-time */
                            started_at?: string | null;
                            status: components["schemas"]["JobStatus"];
                            trace_span_id?: string | null;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Job store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cancel failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_llm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured LLM provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_logs: {
        parameters: {
            query?: {
                level?: components["schemas"]["LogLevel"];
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of recent log records, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stream_logs: {
        parameters: {
            query?: {
                level?: components["schemas"]["LogLevel"];
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream of LogEntry JSON — one `log` event per newly captured record matching the filters. Emits `lagged` if the subscriber can't keep up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_memory: {
        parameters: {
            query?: {
                user_id?: string;
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching memory entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            category: components["schemas"]["MemoryCategory"];
                            content: string;
                            /** Format: date-time */
                            created_at: string;
                            embedding?: number[] | null;
                            /** Format: date-time */
                            expires_at?: string | null;
                            id: string;
                            /** Format: float */
                            importance: number;
                            /** Format: date-time */
                            last_accessed: string;
                            source_session_id?: string | null;
                            user_id: string;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    store_memory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreMemoryRequest"];
            };
        };
        responses: {
            /** @description Stored memory entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntry"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory entry id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory entry deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_skills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered skill names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: string[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered tool manifests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            description: string;
                            name: string;
                            parameters_schema: Record<string, never>;
                        }[];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id whose trace to export */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Raw trace tree for the session. Shape mirrors `aura_trace::TraceNode` but is emitted as untyped JSON to keep the admin surface decoupled from internal trace crate changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No trace for that session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
