/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_sessions"];
        put?: never;
        post: operations["create_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_session"];
        put?: never;
        post?: never;
        delete: operations["delete_session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/sessions/{session_id}/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_session_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/sessions/{session_id}/unhide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["unhide_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/slash-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["slash_manifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_config"];
        put: operations["set_config"];
        post?: never;
        delete: operations["unset_config"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_cron"];
        put?: never;
        post: operations["create_cron"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cron/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_cron"];
        put?: never;
        post?: never;
        delete: operations["delete_cron"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_llm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["set_default"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_model"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/models/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stream_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_memory"];
        put?: never;
        post: operations["store_memory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/memory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_memory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_skills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_traces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/traces/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_trace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description One bucket per UTC day for the analytics chart.
         *
         *     `cost_micro_usd` is integer micro-USD (USD × 10^6). Rendering layers
         *     divide by 1_000_000 to get USD; on-wire arithmetic stays exact.
         */
        AnalyticsDayBucket: {
            cache_creation_input_tokens: number;
            cached_input_tokens: number;
            /**
             * Format: int64
             * @description Spend for the day, in **micro-USD** (1 USD = 1_000_000).
             */
            cost_micro_usd: number;
            /** @description `YYYY-MM-DD` (UTC). */
            date: string;
            input_tokens: number;
            output_tokens: number;
            sessions_created: number;
        };
        /** @description Per-model breakdown row for the analytics dashboard. */
        AnalyticsModelBucket: {
            cache_creation_input_tokens: number;
            cached_input_tokens: number;
            call_count: number;
            /**
             * Format: int64
             * @description Spend for the model, in **micro-USD** (1 USD = 1_000_000).
             */
            cost_micro_usd: number;
            input_tokens: number;
            model: string;
            output_tokens: number;
        };
        /** @description `GET /v1/analytics` response body. */
        AnalyticsResponse: {
            by_model: components["schemas"]["AnalyticsModelBucket"][];
            daily: components["schemas"]["AnalyticsDayBucket"][];
            /**
             * Format: date-time
             * @description Inclusive lower bound used for the aggregation (UTC).
             */
            since: string;
            total_cache_creation_input_tokens: number;
            total_cached_input_tokens: number;
            /**
             * Format: int64
             * @description Total spend across the window, in **micro-USD** (1 USD = 1_000_000).
             */
            total_cost_micro_usd: number;
            total_input_tokens: number;
            total_output_tokens: number;
            total_record_count: number;
            /**
             * Format: date-time
             * @description Exclusive upper bound used for the aggregation (UTC).
             */
            until: string;
        };
        /**
         * @description Admin-surface mirror of [`aura_model::ChannelType`]. Transparent
         *     wrapper around a snake_case string so the OpenAPI surface stays
         *     stable while the core type is open-ended (runtime-registered
         *     sidecars like `"slack"` pass through unchanged).
         */
        ChannelType: string;
        /**
         * @description Response from `POST /v1/chat/sessions` and the
         *     `POST /v1/chat/sessions/:id/token` token-refresh endpoint. Carries
         *     the freshly-minted channel-token the web client presents on its
         *     `/v1/channel-ws` upgrade via the
         *     [`CHANNEL_TOKEN_HEADER`](crate::auth::CHANNEL_TOKEN_HEADER) header
         *     (or the `?token=` query when the browser's WebSocket API can't set
         *     custom headers — which it never can).
         */
        ChatSessionCredential: {
            /**
             * @description Capability token bound to a `web/<uuid>` identity. Live for the
             *     lifetime of the session row; calling
             *     `POST /v1/chat/sessions/:id/token` revokes the previous token
             *     and returns a new one.
             */
            channel_token: string;
            /**
             * @description Header name the web client must use when presenting the
             *     channel-token on the channel listener.
             */
            channel_token_header: string;
            /** @description New (or existing) session id. */
            session_id: string;
        };
        ChatSessionDetail: {
            /** Format: date-time */
            created_at: string;
            /**
             * @description `true` when at least one older active row exists below the
             *     slice's lowest ordinal — i.e. the client should keep
             *     scroll-up pagination armed. `false` when the slice already
             *     includes the session's first message.
             */
            has_more: boolean;
            hidden: boolean;
            /** Format: date-time */
            last_active: string;
            session_id: string;
            /**
             * @description Active transcript slice, oldest-first within the page. The
             *     server returns at most `limit` rows; older rows are fetched
             *     by passing the lowest `ordinal` here back as the next
             *     request's `before_ordinal`.
             */
            transcript: components["schemas"]["ChatTranscriptItem"][];
        };
        ChatSessionSummary: {
            /** Format: date-time */
            created_at: string;
            /**
             * @description True when the user has hidden this session from their chat
             *     list. Only ever populated in responses when
             *     `include_hidden=true` was requested.
             */
            hidden?: boolean;
            /** Format: date-time */
            last_active: string;
            session_id: string;
        };
        ChatSessionsList: {
            items: components["schemas"]["ChatSessionSummary"][];
        };
        /**
         * @description One transcript row, flattened from `ChatMessage` into a shape the
         *     web client can render without re-implementing the content-block
         *     matcher.
         */
        ChatTranscriptItem: {
            /**
             * @description `true` when this row had non-text content (image / audio /
             *     file). The web client currently shows a placeholder.
             */
            has_attachments: boolean;
            /**
             * Format: int64
             * @description Absolute `session_messages.ordinal` of this row. Stable for the
             *     lifetime of the session and used both as a React key and as
             *     the `before_ordinal` cursor for the next-older page request.
             */
            ordinal: number;
            /**
             * @description `"user"` or `"assistant"` (or `"system"`). String rather than
             *     enum to keep the wire forgiving.
             */
            role: string;
            /**
             * @description Plain text content, newline-joined when multiple text blocks
             *     were present. Empty when the message was media-only.
             */
            text: string;
        };
        /**
         * @description `POST /v1/cron` body. Schedule format is the standard 5-field cron
         *     string accepted by [`aura_cron`].
         */
        CreateCronRequest: {
            channel?: null | components["schemas"]["ChannelType"];
            origin_session_id?: string | null;
            schedule: string;
            text: string;
            /**
             * @description IANA timezone (e.g. `"Asia/Shanghai"`) used to evaluate the cron
             *     expression and to render time fields in responses. Required —
             *     every time the API speaks is anchored to this zone, so callers
             *     must commit to one explicitly.
             */
            timezone: string;
            user_id: string;
        };
        /** @description Mirror of [`aura_cron::CronJob`]. */
        CronJob: {
            channel: components["schemas"]["ChannelType"];
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: date-time */
            last_triggered_at?: string | null;
            /** Format: date-time */
            next_trigger_at?: string | null;
            origin_session_id?: string | null;
            prompt: string;
            schedule: components["schemas"]["CronSchedule"];
            status: components["schemas"]["CronStatus"];
            timezone: string;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        /** @description Mirror of [`aura_cron::CronSchedule`]. */
        CronSchedule: {
            expr: string;
            /** @enum {string} */
            kind: "cron";
        } | {
            /** @enum {string} */
            kind: "at";
            /** Format: date-time */
            time: string;
        };
        /**
         * @description Mirror of [`aura_cron::CronStatus`].
         * @enum {string}
         */
        CronStatus: "enabled" | "disabled" | "executed";
        /**
         * @description Uniform error envelope for every non-2xx admin response.
         *
         *     `GatewayError::into_response` already emits `{"error": "..."}`; this
         *     type just pins the shape in the spec so clients can discriminate on
         *     it rather than on status codes alone.
         */
        ErrorBody: {
            error: string;
        };
        /**
         * @description Wire mirror of [`aura_job::Job`]. Inner shape reflects the new
         *     state machine (Q6) — `final_result` replaces `output`/`error`,
         *     `emitted_span_ids` replaces `trace_span_id`.
         */
        Job: {
            /** Format: date-time */
            created_at: string;
            effective_soul_version: string;
            emitted_span_ids: string[];
            /** Format: date-time */
            ended_at?: string | null;
            final_result?: Record<string, never> | null;
            id: string;
            kind: components["schemas"]["JobKind"];
            parent_job_id?: string | null;
            session_id: string;
            /** Format: date-time */
            started_at?: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * @description Wire mirror of [`aura_job::JobKind`].
         * @enum {string}
         */
        JobKind: "user_chat" | "cron" | "system" | "spawned";
        /**
         * @description Wire mirror of [`aura_job::JobStatus`]. Carries the same payload
         *     the domain enum carries (cancel reason, partial-artifact span IDs);
         *     the wire shape collapses inner-variant content into `Option`-typed
         *     fields so HTTP clients can decode without needing the full Rust
         *     enum machinery.
         */
        JobStatus: {
            cancel_reason?: string | null;
            kind: components["schemas"]["JobStatusKind"];
            partial_artifacts?: string[];
            reason?: string | null;
        };
        /** @enum {string} */
        JobStatusKind: "pending" | "in_progress" | "stuck" | "cancelled" | "failed" | "completed";
        /**
         * @description Envelope for list endpoints. `next_cursor` is opaque — clients
         *     pass it back as `?cursor=` to fetch the next page, and treat
         *     `None` as "no more pages." The cursor's internal scheme may change
         *     across releases; clients must not parse it.
         */
        ListResponse_SlashCommandEntry: {
            items: {
                command: string;
                description: string;
            }[];
            next_cursor?: string | null;
        };
        /** @description Current LLM provider descriptor. */
        LlmInfo: {
            model_id: string;
            provider: string;
        };
        /**
         * @description One row in `GET /v1/llm/models`. Carries both the raw config (so the
         *     edit form can populate "override or unset" toggles) and the
         *     **effective** values that result from layering overrides over the
         *     factory / OpenRouter snapshot defaults.
         */
        LlmModelEntry: {
            /**
             * @description `true` when an API key is currently resolvable for this entry
             *     (vault entry, explicit `api_key_env`, or provider-default env
             *     var). The literal value never leaves the gateway.
             */
            api_key_configured: boolean;
            api_key_env?: string | null;
            base_url?: string | null;
            /** @description Operator override for `context_window`. `None` = factory default. */
            context_window_override?: number | null;
            /**
             * @description Effective `context_window` that the runtime would observe given
             *     the current overrides and snapshot/factory defaults.
             */
            effective_context_window: number;
            /** @description Effective pricing. */
            effective_pricing: components["schemas"]["LlmModelPricingDto"];
            /** @description Effective vision flag. */
            effective_supports_vision: boolean;
            is_default: boolean;
            model: string;
            name: string;
            pricing_override?: null | components["schemas"]["LlmPricingOverrideDto"];
            provider: string;
            reasoning_effort?: string | null;
            /** @description Operator override for `supports_vision`. `None` = factory default. */
            supports_vision_override?: boolean | null;
        };
        /**
         * @description Effective per-token pricing for a model after applying any operator
         *     overrides — micro-USD per 1M tokens.
         */
        LlmModelPricingDto: {
            /** Format: int64 */
            cache_write_per_1m_tokens?: number | null;
            /** Format: int64 */
            cached_input_per_1m_tokens?: number | null;
            /** Format: int64 */
            input_per_1m_tokens: number;
            /** Format: int64 */
            output_per_1m_tokens: number;
        };
        /**
         * @description `POST /v1/llm/models/{name}/test` response. Carries the latency and
         *     token usage from a one-shot `ping` probe.
         */
        LlmModelTestResult: {
            /**
             * @description On `ok: false`, a human-readable error suitable for direct
             *     display (auth failure, network error, etc.).
             */
            error?: string | null;
            input_tokens?: number | null;
            /**
             * Format: int64
             * @description Round-trip latency in ms (only on success).
             */
            latency_ms?: number | null;
            model: string;
            ok: boolean;
            output_tokens?: number | null;
            /**
             * @description Provider id used for the probe (may differ from the request's
             *     `name` if the entry's provider was just edited).
             */
            provider: string;
        };
        /**
         * @description One row in `GET /v1/llm/usage` — aggregated cost / token volume for
         *     a single configured entry, joined by `entry.model == record.model`.
         */
        LlmModelUsage: {
            cache_creation_input_tokens: number;
            cached_input_tokens: number;
            call_count: number;
            /** Format: int64 */
            cost_micro_usd: number;
            input_tokens: number;
            /** @description The `model` id used to look up records. */
            model: string;
            /** @description Entry `name`. May be unique per (provider, model) pair. */
            name: string;
            output_tokens: number;
        };
        /** @description `GET /v1/llm/models` response. */
        LlmModelsResponse: {
            default_name: string;
            items: components["schemas"]["LlmModelEntry"][];
        };
        /**
         * @description Per-entry pricing override fields. Wire shape mirrors
         *     [`aura_model::LlmPricingOverride`]; each field is integer micro-USD
         *     per 1M tokens (1 USD = 1_000_000). The DTO exists separately from
         *     the canonical struct only so we can derive `ToSchema` for utoipa
         *     without leaking that derive into `aura-model`.
         */
        LlmPricingOverrideDto: {
            /** Format: int64 */
            cache_write_per_1m_tokens?: number | null;
            /** Format: int64 */
            cached_input_per_1m_tokens?: number | null;
            /** Format: int64 */
            input_per_1m_tokens?: number | null;
            /** Format: int64 */
            output_per_1m_tokens?: number | null;
        };
        /** @description `GET /v1/llm/usage` response. */
        LlmUsageResponse: {
            items: components["schemas"]["LlmModelUsage"][];
            /**
             * Format: date-time
             * @description Inclusive lower bound of the aggregation window.
             */
            since: string;
            /**
             * Format: date-time
             * @description Exclusive upper bound.
             */
            until: string;
        };
        /**
         * @description Mirror of [`crate::log_buffer::LogRecord`]. Used as the item type of
         *     [`LogsResponse`].
         */
        LogEntry: {
            fields: components["schemas"]["LogField"][];
            /** Format: int64 */
            id: number;
            level: components["schemas"]["LogLevel"];
            message: string;
            /**
             * @description Tracing target that emitted the record (e.g.
             *     `aura_gateway::server`). Rendered as "source" in the UI.
             */
            target: string;
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * @description Single structured tracing field (`k=v`) captured alongside a log
         *     record. Kept as free-form strings — formatting / unquoting happens
         *     in the emitter.
         */
        LogField: {
            name: string;
            value: string;
        };
        /**
         * @description Mirror of [`crate::log_buffer::LogLevel`]. Snake-cased on the wire to
         *     match the rest of the admin surface.
         * @enum {string}
         */
        LogLevel: "error" | "warn" | "info" | "debug" | "trace";
        /**
         * @description Envelope for `GET /v1/logs`. Unlike [`ListResponse`] we expose
         *     `total` so the UI can render pagination (`Showing X of N`).
         */
        LogsResponse: {
            items: components["schemas"]["LogEntry"][];
            /**
             * @description Total number of records matching the filters — independent of
             *     `limit`/`offset`, so clients can size the pager without asking
             *     for the full list.
             */
            total: number;
        };
        MemoryCategory: {
            /** @enum {string} */
            type: "UserPreference" | "KeyFact";
        };
        /** @description Mirror of [`aura_model::MemoryEntry`]. */
        MemoryEntry: {
            category: components["schemas"]["MemoryCategory"];
            content: string;
            /** Format: date-time */
            created_at: string;
            embedding?: number[] | null;
            /** Format: date-time */
            expires_at?: string | null;
            id: string;
            /** Format: float */
            importance: number;
            /** Format: date-time */
            last_accessed: string;
            source_session_id?: string | null;
            user_id: string;
        };
        /** @description Response body for `PUT` / `DELETE /v1/config`. */
        MutateResponse: {
            path: string;
            requires_restart: boolean;
            written_to: string;
        };
        /** @description `PUT /v1/config` body. */
        SetConfigRequest: {
            path: string;
            /** @description JSON value written at `path`. Shape validated by `AuraConfig`. */
            value: Record<string, never>;
        };
        /** @description `PUT /v1/llm/default` body. */
        SetDefaultLlmRequest: {
            name: string;
        };
        /**
         * @description Wire DTO for slash command entries. Mirror of
         *     [`aura_channels::wire::SlashCommandSpec`] so the OpenAPI surface
         *     stays inside this crate's DTOs (the wire type lives in
         *     `aura-channels` for sidecar reuse).
         */
        SlashCommandEntry: {
            command: string;
            description: string;
        };
        /** @description Minimal gateway health/status payload. */
        StatusResponse: {
            bind_address: string;
            jobs_in_flight: number;
            sessions: number;
            version: string;
        };
        /** @description `POST /v1/memory` body. */
        StoreMemoryRequest: {
            content: string;
            /** Format: float */
            importance?: number | null;
            user_id?: string | null;
        };
        /**
         * @description One row of the trace browser list view. Mirrors
         *     [`aura_agent::SessionSummary`] for the wire.
         */
        TraceSessionSummary: {
            cache_creation_input_tokens: number;
            cached_input_tokens: number;
            /** Format: date-time */
            created_at: string;
            input_tokens: number;
            job_count: number;
            /** Format: date-time */
            last_active: string;
            latest_job_status?: null | components["schemas"]["JobStatus"];
            output_tokens: number;
            session_id: string;
            span_count: number;
        };
        /**
         * @description Envelope for `GET /v1/traces`. Carries `total` for "Showing X of N"
         *     pagers, matching the shape of [`LogsResponse`].
         */
        TracesListResponse: {
            items: components["schemas"]["TraceSessionSummary"][];
            total: number;
        };
        /** @description `DELETE /v1/config` body. */
        UnsetConfigRequest: {
            path: string;
        };
        /**
         * @description `PUT /v1/llm/models/{name}` body. Every field is optional — only
         *     present fields are applied. To clear an override pass an explicit
         *     `null` (handled by including the key in the request JSON; serde
         *     can't distinguish "missing key" from "key with null" by default, so
         *     the handler treats `Some(None)` as clear and an absent key as keep).
         */
        UpdateLlmModelRequest: {
            /**
             * @description Set the literal API key in the vault (`llm.entry.<name>.api_key`).
             *     Pass `""` to remove the vault entry, or omit the field to leave
             *     the vault untouched. Never echoed back.
             */
            api_key?: string | null;
            /** @description Environment variable name holding the API key, or `null` to clear. */
            api_key_env?: string | null;
            /** @description Custom base URL or `null` to clear. */
            base_url?: string | null;
            /** @description `context_window` override, or `null` to clear. */
            context_window?: number | null;
            /** @description Set the model id (e.g. `"gpt-4o"`). Requires gateway restart. */
            model?: string | null;
            pricing?: null | components["schemas"]["LlmPricingOverrideDto"];
            /** @description Set the provider id (e.g. `"openai"`). Requires gateway restart. */
            provider?: string | null;
            /** @description Reasoning-effort override, or `null` to clear. */
            reasoning_effort?: string | null;
            /** @description `supports_vision` override, or `null` to clear. */
            supports_vision?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analytics: {
        parameters: {
            query?: {
                since?: string;
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated tokens / cost / sessions over the time range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            channel_type: components["schemas"]["ChannelType"];
                            status: string;
                        }[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_sessions: {
        parameters: {
            query?: {
                /** @description Include hidden sessions in the response. Defaults to false. */
                include_hidden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Web chat sessions, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionsList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New session id + freshly-minted channel-token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionCredential"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Session creation or token mint failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_session: {
        parameters: {
            query?: {
                /**
                 * @description Return only rows whose `ordinal` is strictly less than this
                 *     value. Omit on the initial fetch; pass the lowest ordinal from
                 *     the prior page to scroll further back. Maps to a primary-key
                 *     range scan over the `session_messages` active index.
                 */
                before_ordinal?: number | null;
                /**
                 * @description Maximum rows to return. Defaults to
                 *     [`DEFAULT_HISTORY_LIMIT`], clamped to [`MAX_HISTORY_LIMIT`].
                 */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Session id to fetch */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail + transcript slice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id to hide */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hidden (row preserved on the server) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    refresh_session_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id whose token to refresh */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fresh channel-token (old one revoked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSessionCredential"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unhide_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id to restore */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unhidden */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    slash_manifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Slash command list for /-autocomplete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListResponse_SlashCommandEntry"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current in-memory config. Secret fields are redacted by `AuraConfig`'s serde impl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetConfigRequest"];
            };
        };
        responses: {
            /** @description Config updated on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Invalid path or value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    unset_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsetConfigRequest"];
            };
        };
        responses: {
            /** @description Config entry removed on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Invalid path */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_cron: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All cron jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            channel: components["schemas"]["ChannelType"];
                            /** Format: date-time */
                            created_at: string;
                            id: string;
                            /** Format: date-time */
                            last_triggered_at?: string | null;
                            /** Format: date-time */
                            next_trigger_at?: string | null;
                            origin_session_id?: string | null;
                            prompt: string;
                            schedule: components["schemas"]["CronSchedule"];
                            status: components["schemas"]["CronStatus"];
                            timezone: string;
                            /** Format: date-time */
                            updated_at: string;
                            user_id: string;
                        }[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Scheduler error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_cron: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCronRequest"];
            };
        };
        responses: {
            /** @description Created cron job */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJob"];
                };
            };
            /** @description Invalid schedule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_cron: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cron job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cron job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronJob"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cron: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cron job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cron job deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Scheduler error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to a single session. Hits the per-session index in
                 *     the store instead of scanning the full jobs table.
                 */
                session?: string | null;
                /**
                 * @description Restrict to one terminal/in-flight status discriminator.
                 *     Snake-case, matching `JobStatusKind` (`pending`, `in_progress`,
                 *     `stuck`, `cancelled`, `failed`, `completed`).
                 */
                status?: string | null;
                /** @description Maximum items to return. Defaults to 50; capped at 500. */
                limit?: number | null;
                /** @description Opaque cursor from a previous response's `next_cursor`. */
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated jobs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            /** Format: date-time */
                            created_at: string;
                            effective_soul_version: string;
                            emitted_span_ids: string[];
                            /** Format: date-time */
                            ended_at?: string | null;
                            final_result?: Record<string, never> | null;
                            id: string;
                            kind: components["schemas"]["JobKind"];
                            parent_job_id?: string | null;
                            session_id: string;
                            /** Format: date-time */
                            started_at?: string | null;
                            status: components["schemas"]["JobStatus"];
                        }[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Invalid query parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Job store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Invalid job id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled job record */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Invalid job id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cancel failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_llm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Currently active LLM provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_default: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDefaultLlmRequest"];
            };
        };
        responses: {
            /** @description `default-llm` updated on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Name does not match any entry */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured LLM entries with their effective settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModelsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entry name (matches `llm[*].name`) */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLlmModelRequest"];
            };
        };
        responses: {
            /** @description Entry updated on disk. Gateway restart required to pick up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutateResponse"];
                };
            };
            /** @description Invalid update */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Write failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    test_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entry name (matches `llm[*].name`) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result — `ok: false` carries the provider's error verbatim */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmModelTestResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_usage: {
        parameters: {
            query?: {
                since?: string;
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-entry usage aggregates over the time range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmUsageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_logs: {
        parameters: {
            query?: {
                level?: components["schemas"]["LogLevel"];
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of recent log records, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogsResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    stream_logs: {
        parameters: {
            query?: {
                level?: components["schemas"]["LogLevel"];
                q?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream of LogEntry JSON — one `log` event per newly captured record matching the filters. Emits `lagged` if the subscriber can't keep up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_memory: {
        parameters: {
            query?: {
                user_id?: string;
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching memory entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            category: components["schemas"]["MemoryCategory"];
                            content: string;
                            /** Format: date-time */
                            created_at: string;
                            embedding?: number[] | null;
                            /** Format: date-time */
                            expires_at?: string | null;
                            id: string;
                            /** Format: float */
                            importance: number;
                            /** Format: date-time */
                            last_accessed: string;
                            source_session_id?: string | null;
                            user_id: string;
                        }[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    store_memory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreMemoryRequest"];
            };
        };
        responses: {
            /** @description Stored memory entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntry"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_memory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Memory entry id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory entry deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Memory store error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_skills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered skill names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: string[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gateway status snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Missing or invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered tool manifests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: {
                            description: string;
                            name: string;
                            parameters_schema: Record<string, never>;
                        }[];
                        next_cursor?: string | null;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_traces: {
        parameters: {
            query?: {
                /** @description Filter on the latest job's status (snake_case enum). */
                status?: components["schemas"]["JobStatusKind"];
                /** @description Inclusive lower bound on `last_active`. */
                since?: string;
                /** @description Exclusive upper bound on `last_active`. */
                until?: string;
                /** @description Case-insensitive substring on session id. */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated session summaries (newest active first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracesListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_trace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id whose trace to export */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-session trace tree: jobs, their steps, and the spans under each step. Untyped JSON to keep the admin surface decoupled from internal trace crate changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description No trace for that session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
