[package]
name = "remote-host"
version.workspace = true
edition.workspace = true

[[bin]]
name = "remote-host"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
remote-host-push = { workspace = true }
remote-host-relay = { workspace = true }
remote-host-serve = { workspace = true }
