//! Bake the bench viewer's React bundle into the `bench-web` binary.
//!
//! Mirrors `crates/gateway/build.rs` but only the WebUI half — this
//! tool ships no sidecars. We run `pnpm --filter aura-bench-web build`
//! to emit `web/dist/`, zstd-compress each asset, and write
//! `$OUT_DIR/webui_assets.rs` with one `include_bytes!` arm per asset.
//! `src/webui.rs` lazily decompresses the table on first request.
//!
//! Degrades gracefully: if `pnpm` is missing or the build chokes, we
//! drop a placeholder `index.html` and emit `cargo:warning=…` so
//! `cargo build` of the backend still succeeds during Rust-only work.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

/// zstd level — matches the gateway's choice. Output is cached by
/// cargo's rerun-if-changed graph, so the build-time cost is paid only
/// when the bundle actually changes.
const ZSTD_LEVEL: i32 = 19;

/// pnpm workspace package name of the bench viewer frontend (its
/// `web/package.json` `name`).
const WEB_PKG: &str = "aura-bench-web";

fn main() {
    let manifest = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"),
    );
    let ws_root = manifest
        .parent()
        .and_then(|p| p.parent())
        .expect("bench-web crate lives under <workspace>/bench/bench-web")
        .to_path_buf();
    let web_root = manifest.join("web");
    let dist = web_root.join("dist");
    let index = dist.join("index.html");

    // Re-run only when the frontend sources (or the lockfile) change.
    emit_rerun_if_changed(&web_root.join("src"));
    for f in [
        web_root.join("index.html"),
        web_root.join("package.json"),
        web_root.join("vite.config.ts"),
        web_root.join("tsconfig.json"),
        web_root.join("tsconfig.app.json"),
        web_root.join("tsconfig.node.json"),
        ws_root.join("pnpm-lock.yaml"),
    ] {
        if f.exists() {
            println!("cargo:rerun-if-changed={}", f.display());
        }
    }

    match build_webui(&ws_root, &web_root) {
        Ok(()) => {}
        Err(e) => println!(
            "cargo:warning=bench-web frontend build failed ({e}); using existing dist or placeholder"
        ),
    }

    if !index.exists() {
        fs::create_dir_all(&dist).expect("create dist directory");
        fs::write(
            &index,
            concat!(
                "<!doctype html><html><head><meta charset=\"utf-8\">",
                "<title>Aura Bench Viewer</title></head>",
                "<body style=\"font-family:monospace;padding:2rem\">",
                "<h1>bench-web frontend not built</h1>",
                "<p>Run <code>pnpm install &amp;&amp; pnpm --filter aura-bench-web build</code>.</p>",
                "</body></html>",
            ),
        )
        .expect("write stub index.html");
    }

    let mut files = Vec::new();
    collect_assets(&dist, &dist, &mut files);
    files.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let generated = out_dir.join("webui_assets.rs");
    let mut out = fs::File::create(&generated).expect("create generated assets file");
    writeln!(out, "// @generated by build.rs — do not edit.").expect("write header");
    writeln!(
        out,
        "pub(super) struct WebAsset {{ pub path: &'static str, pub mime: &'static str, pub content_zst: &'static [u8] }}",
    )
    .expect("write struct");
    writeln!(out, "pub(super) const ASSETS: &[WebAsset] = &[").expect("write array open");
    for (idx, (rel, abs)) in files.iter().enumerate() {
        let mime = mime_for(rel);
        let zst_path = out_dir.join(zst_name(idx, rel));
        compress_file(abs, &zst_path).expect("compress web asset");
        writeln!(
            out,
            "    WebAsset {{ path: {rel:?}, mime: {mime:?}, content_zst: include_bytes!({zst_path:?}) }},",
        )
        .expect("write asset");
    }
    writeln!(out, "];").expect("write array close");
}

fn build_webui(ws_root: &Path, web_root: &Path) -> Result<(), String> {
    // Best-effort install only when node_modules is absent, to avoid
    // racing the gateway's build.rs (which owns the shared install).
    if !ws_root.join("node_modules/.modules.yaml").exists() {
        let _ = Command::new("pnpm")
            .arg("install")
            .current_dir(ws_root)
            .env("CI", "1")
            .env("npm_config_confirm_modules_purge", "false")
            .output()
            .map_err(|e| format!("spawn pnpm install: {e}"))?;
    }
    // The frontend imports committed ts-rs bindings under
    // web/src/generated/. If they're missing the tsc step fails — that
    // is intentional (regenerate via scripts/check-ts-bindings.sh).
    if !web_root.join("src/generated").exists() {
        return Err("web/src/generated missing — run scripts/check-ts-bindings.sh".to_string());
    }
    let output = Command::new("pnpm")
        .arg("--filter")
        .arg(WEB_PKG)
        .arg("build")
        .current_dir(ws_root)
        .output()
        .map_err(|e| format!("spawn pnpm: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "pnpm build exited {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr),
        ));
    }
    Ok(())
}

fn collect_assets(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(reader) = fs::read_dir(dir) else {
        return;
    };
    for entry in reader.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_assets(base, &path, out);
        } else if let Ok(rel) = path.strip_prefix(base) {
            out.push((rel.to_string_lossy().replace('\\', "/"), path));
        }
    }
}

fn mime_for(path: &str) -> &'static str {
    let ext = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    match ext.as_str() {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

fn zst_name(index: usize, rel: &str) -> String {
    let mut s = String::with_capacity(rel.len());
    for ch in rel.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch);
        } else {
            s.push('_');
        }
    }
    format!("webui-{index:04}-{s}.zst")
}

fn compress_file(src: &Path, dst: &Path) -> Result<(), String> {
    let data = fs::read(src).map_err(|e| format!("read {}: {e}", src.display()))?;
    let compressed = zstd::bulk::compress(&data, ZSTD_LEVEL)
        .map_err(|e| format!("zstd compress {}: {e}", src.display()))?;
    fs::write(dst, &compressed).map_err(|e| format!("write {}: {e}", dst.display()))
}

fn emit_rerun_if_changed(path: &Path) {
    if !path.exists() {
        return;
    }
    println!("cargo:rerun-if-changed={}", path.display());
    if !path.is_dir() {
        return;
    }
    if let Ok(reader) = fs::read_dir(path) {
        for entry in reader.flatten() {
            emit_rerun_if_changed(&entry.path());
        }
    }
}
