[package]
name = "baybo-project"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
baybo-model = { workspace = true }
baybo-store = { workspace = true }
baybo-workspace = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "process"] }
tracing = { workspace = true }

[dev-dependencies]
baybo-storage = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
