use std::net::{Ipv4Addr, Ipv6Addr, SocketAddr};

use serde::{Deserialize, Serialize};

/// `gateway.direct_udp`: the gateway's direct-carrier UDP sockets, one per
/// address family (see `docs/modules/mobile/direct-carriers.md`). On by
/// default whenever a relay binding exists; `enabled: false` is the off
/// switch, and a `null` bind leaves that family unbound.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(default)]
pub struct DirectUdpConfig {
    pub enabled: bool,
    pub ipv4_bind: Option<SocketAddr>,
    pub ipv6_bind: Option<SocketAddr>,
}

impl Default for DirectUdpConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            ipv4_bind: Some(SocketAddr::from((Ipv4Addr::UNSPECIFIED, 0))),
            ipv6_bind: Some(SocketAddr::from((Ipv6Addr::UNSPECIFIED, 0))),
        }
    }
}

/// HTTP gateway configuration.
///
/// The gateway runs two listeners:
///
/// * **Admin** on TCP (`bind_address`:`port`) with bearer-token auth
///   for the REST surface (config / status / turns / cron / memory /
///   traces / skills / tools / llm and a read-only channel list) and
///   channel-token auth for the co-hosted `/v1/channel-ws` upgrade.
///   The TUI and the browser-side web chat page both dial this same
///   bind.
/// * **Channel** on loopback TCP (`127.0.0.1:<ephemeral>`, hardcoded
///   — not configurable) with channel-token auth backed by the
///   gateway's `ChannelTokenTable` (per-spawn subprocess capability
///   tokens). Used only by gateway-spawned sidecars; the chosen port
///   is published to `<workspace>/state/channel.port` and handed to
///   each child via its launch URL. Mounts the same `/v1/channel-ws`
///   endpoint the admin listener exposes.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct GatewayConfig {
    /// When false, `baybo gateway start` still runs, but the service unit
    /// generated by `install`/`enable` warns that the section is disabled.
    pub enabled: bool,
    /// Admin TCP listener bind address.
    pub bind_address: String,
    /// Admin TCP listener port.
    pub port: u16,
    /// CORS origins permitted by the admin listener. Empty = no
    /// CORS headers emitted. CORS is meaningless on the loopback
    /// channel listener and is not applied there.
    pub cors_allowed_origins: Vec<String>,
    /// Seconds the process waits for graceful shutdown before the
    /// force-exit watchdog kicks in.
    pub shutdown_grace_secs: u64,
    pub direct_udp: DirectUdpConfig,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            bind_address: "127.0.0.1".into(),
            port: 8888,
            cors_allowed_origins: Vec::new(),
            shutdown_grace_secs: 30,
            direct_udp: DirectUdpConfig::default(),
        }
    }
}
