use serde::{Deserialize, Serialize};

/// HTTP gateway configuration.
///
/// Controls the standalone HTTP server launched by `aura gateway start`.
/// The gateway both hosts a `ChannelAdapter` (so chat flows through the
/// normal Router path) and exposes an admin REST/SSE API.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct GatewayConfig {
    /// When false, `aura gateway start` still runs, but the service unit
    /// generated by `install`/`enable` warns that the section is disabled.
    pub enabled: bool,
    pub bind_address: String,
    pub port: u16,
    /// CORS origins permitted by the server. Empty = no CORS headers emitted.
    pub cors_allowed_origins: Vec<String>,
    /// Seconds the process waits for graceful shutdown before the force-exit
    /// watchdog kicks in.
    pub shutdown_grace_secs: u64,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            bind_address: "127.0.0.1".into(),
            port: 8888,
            cors_allowed_origins: Vec::new(),
            shutdown_grace_secs: 30,
        }
    }
}
