use serde::{Deserialize, Serialize};

/// HTTP gateway configuration.
///
/// The gateway runs two listeners:
///
/// * **Admin** on TCP (`bind_address`:`port`) with a bearer token —
///   config / status / jobs / cron / memory / traces / skills / tools /
///   llm and a read-only channel list.
/// * **Channel** on a Unix domain socket under the per-workspace
///   identity directory (`<workspace>/channel.sock`, not configurable)
///   with peer-credential + PSK/token auth — sessions, messages,
///   approvals, SSE streams. The TUI and future sidecar channel plugins
///   talk to this listener.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(default)]
pub struct GatewayConfig {
    /// When false, `aura gateway start` still runs, but the service unit
    /// generated by `install`/`enable` warns that the section is disabled.
    pub enabled: bool,
    /// Admin TCP listener bind address.
    pub bind_address: String,
    /// Admin TCP listener port.
    pub port: u16,
    /// CORS origins permitted by the admin listener. Empty = no CORS
    /// headers emitted. CORS is meaningless on the UDS listener and is
    /// not applied there.
    pub cors_allowed_origins: Vec<String>,
    /// Seconds the process waits for graceful shutdown before the
    /// force-exit watchdog kicks in.
    pub shutdown_grace_secs: u64,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            bind_address: "127.0.0.1".into(),
            port: 8888,
            cors_allowed_origins: Vec::new(),
            shutdown_grace_secs: 30,
        }
    }
}
