// Compile-time drift sentinel — type-only, produces no runtime output.
//
// `browserViewTypes.ts` hand-mirrors the browser live-view wire contract
// (the dashboard does not depend on the sidecar package); the authoritative
// TS is generated by ts-rs from `crates/browser-view/src/wire.rs` into
// `sidecars/tool/browser/src/generated/`, CI-gated by
// `scripts/check-ts-bindings.sh`. Same pattern as `wireSentinel.ts`.
//
// Every shape here is plain JSON with no `bigint`, so the check is MUTUAL
// assignability: a field added, removed, renamed or retyped on either side
// fails `tsc -b`.
import type { BrowserMode as GenBrowserMode } from '../../../../sidecars/tool/browser/src/generated/BrowserMode';
import type { BrowserPhase as GenBrowserPhase } from '../../../../sidecars/tool/browser/src/generated/BrowserPhase';
import type { BrowserStatus as GenBrowserStatus } from '../../../../sidecars/tool/browser/src/generated/BrowserStatus';
import type { DockerPhase as GenDockerPhase } from '../../../../sidecars/tool/browser/src/generated/DockerPhase';
import type { FrameHeader as GenFrameHeader } from '../../../../sidecars/tool/browser/src/generated/FrameHeader';
import type { StreamState as GenStreamState } from '../../../../sidecars/tool/browser/src/generated/StreamState';
import type { StreamStatus as GenStreamStatus } from '../../../../sidecars/tool/browser/src/generated/StreamStatus';
import type { TargetInfo as GenTargetInfo } from '../../../../sidecars/tool/browser/src/generated/TargetInfo';
import type { TargetsMsg as GenTargetsMsg } from '../../../../sidecars/tool/browser/src/generated/TargetsMsg';
import type { UnavailableReason as GenUnavailableReason } from '../../../../sidecars/tool/browser/src/generated/UnavailableReason';
import type { ViewerDown as GenViewerDown } from '../../../../sidecars/tool/browser/src/generated/ViewerDown';
import type { ViewerErrorCode as GenViewerErrorCode } from '../../../../sidecars/tool/browser/src/generated/ViewerErrorCode';
import type { ViewerUp as GenViewerUp } from '../../../../sidecars/tool/browser/src/generated/ViewerUp';
import type {
  BrowserMode,
  BrowserPhase,
  BrowserStatus,
  DockerPhase,
  FrameHeader,
  StreamState,
  StreamStatus,
  TargetInfo,
  TargetsMsg,
  UnavailableReason,
  ViewerDown,
  ViewerErrorCode,
  ViewerUp,
} from './browserViewTypes';

type Assert<T extends true> = T;

/** Non-distributive mutual assignability, plus key-set equality: excess keys
 *  are ignored by plain type-to-type assignability, so an optional field the
 *  mirror declares but the wire dropped would otherwise slip through. */
type Same<A, B> = [A] extends [B]
  ? [B] extends [A]
    ? [keyof A] extends [keyof B]
      ? [keyof B] extends [keyof A]
        ? true
        : false
      : false
    : false
  : false;

/** Per-variant check for tagged unions: each `type` tag on either side must
 *  exist on the other with the same shape. */
type SameUnion<A extends { type: string }, B extends { type: string }> = Same<
  A['type'],
  B['type']
> extends true
  ? [
      {
        [K in A['type']]: Same<Extract<A, { type: K }>, Extract<B, { type: K }>> extends true
          ? never
          : K;
      }[A['type']],
    ] extends [never]
    ? true
    : false
  : false;

export type BrowserModeHolds = Assert<Same<BrowserMode, GenBrowserMode>>;
export type DockerPhaseHolds = Assert<Same<DockerPhase, GenDockerPhase>>;
export type BrowserPhaseHolds = Assert<SameUnion<BrowserPhase, GenBrowserPhase>>;
export type BrowserStatusHolds = Assert<Same<BrowserStatus, GenBrowserStatus>>;
export type TargetInfoHolds = Assert<Same<TargetInfo, GenTargetInfo>>;
export type TargetsMsgHolds = Assert<Same<TargetsMsg, GenTargetsMsg>>;
export type StreamStateHolds = Assert<Same<StreamState, GenStreamState>>;
export type StreamStatusHolds = Assert<Same<StreamStatus, GenStreamStatus>>;
export type UnavailableReasonHolds = Assert<Same<UnavailableReason, GenUnavailableReason>>;
export type ViewerErrorCodeHolds = Assert<Same<ViewerErrorCode, GenViewerErrorCode>>;
export type FrameHeaderHolds = Assert<Same<FrameHeader, GenFrameHeader>>;
export type ViewerDownHolds = Assert<SameUnion<ViewerDown, GenViewerDown>>;
export type ViewerUpHolds = Assert<SameUnion<ViewerUp, GenViewerUp>>;

// Negative controls: deliberately drifted shapes must FAIL the same checks,
// guarding the sentinel against ever becoming vacuously true.
type PoisonedHeader = Omit<FrameHeader, 'seq'> & { seq: string };
// @ts-expect-error — a retyped field must be caught
export type NegativeControlRetype = Assert<Same<PoisonedHeader, GenFrameHeader>>;
type ExtraKeyTargets = TargetsMsg & { bogus?: string };
// @ts-expect-error — a mirror-only optional field must be caught
export type NegativeControlExtraKey = Assert<Same<ExtraKeyTargets, GenTargetsMsg>>;
type MissingVariant = Exclude<ViewerDown, { type: 'pong' }>;
// @ts-expect-error — a dropped union variant must be caught
export type NegativeControlVariant = Assert<SameUnion<MissingVariant, GenViewerDown>>;
