// Hand-written mirror of the browser live-view wire contract. The source of
// truth is `crates/browser-view/src/wire.rs`, generated by ts-rs into
// `sidecars/tool/browser/src/generated/`; the dashboard does not depend on the
// sidecar package, so `browserViewSentinel.ts` pins this mirror to the
// generated files at compile time.
//
// An `Option` field on the Rust side arrives as a required `T | null`.

export type BrowserMode = 'host' | 'docker' | 'cdp_url';

export type DockerPhase =
  | 'docker-checking'
  | 'docker-building-image'
  | 'docker-starting-container'
  | 'docker-waiting-for-cdp';

export type BrowserPhase =
  | { type: 'idle' }
  | { type: 'installing'; percent: number }
  | { type: 'docker'; phase: DockerPhase }
  | { type: 'ready' }
  | { type: 'recovering' }
  | { type: 'failed'; error: string };

export interface BrowserStatus {
  mode: BrowserMode;
  phase: BrowserPhase;
  browser_gen: number;
}

export interface TargetInfo {
  target_id: string;
  url: string;
  title: string;
}

export interface TargetsMsg {
  browser_gen: number;
  targets: TargetInfo[];
  followed: string | null;
}

export type StreamState = 'idle' | 'live' | 'background' | 'target_gone' | 'paused' | 'unavailable';

export interface StreamStatus {
  state: StreamState;
  browser_gen: number;
  target: TargetInfo | null;
}

export type UnavailableReason = 'tap_not_fired' | 'cddm_version_mismatch' | 'browser_disabled';

export type ViewerErrorCode = 'too_many_viewers' | 'bad_message' | 'takeover_disabled';

export interface LinkMsg {
  type: 'link';
  up: boolean;
  link_epoch: number;
  unavailable: UnavailableReason | null;
  ping_interval_ms: number;
}

/** Gateway → viewer JSON text messages. */
export type ViewerDown =
  | LinkMsg
  | ({ type: 'status' } & BrowserStatus)
  | ({ type: 'targets' } & TargetsMsg)
  | ({ type: 'stream' } & StreamStatus)
  | { type: 'error'; code: ViewerErrorCode }
  | { type: 'pong' };

/** Viewer → gateway JSON text messages. */
export type ViewerUp = { type: 'ping' } | { type: 'request_control' };

/** Metadata in front of every screencast JPEG (WS binary message). */
export interface FrameHeader {
  target_id: string;
  browser_gen: number;
  seq: number;
  captured_at_ms: number;
  device_width: number;
  device_height: number;
  offset_top: number;
  page_scale_factor: number;
  scroll_offset_x: number;
  scroll_offset_y: number;
}
