// Compile-time drift sentinel — type-only, produces no runtime output.
//
// `chatWs.ts` hand-mirrors the wire `Frame` union (the shipped channel-ts SDK
// targets Node, so its types aren't imported directly); the authoritative TS
// contract is generated by ts-rs from `crates/wire` into
// `sidecars/sdk/channel-ts/src/generated/`, CI-gated by
// `scripts/check-ts-bindings.sh`. This file pins the mirror to that contract
// so a wire-side rename/retype fails `tsc -b` instead of silently
// misrendering frames at runtime.
//
// Direction matters: for frames the page RECEIVES, the generated
// (runtime-true) shape must be assignable to the hand-written one it is read
// as; for frames the page SENDS, the hand-written shape it encodes must be
// assignable to the generated one the server decodes. `message` / `messages`
// / `ping` / `pong` flow both ways and sit in both lists.
import type { Frame as GeneratedFrame } from '../../../../sidecars/sdk/channel-ts/src/generated/Frame';
import type { Message } from '../../../../sidecars/sdk/channel-ts/src/generated/Message';
import type { WireAttachment as GeneratedAttachment } from '../../../../sidecars/sdk/channel-ts/src/generated/WireAttachment';
import type { Frame, WireAttachment, WireMessage } from './chatWs';

/** ts-rs maps u64/i64 to `bigint` — right for the SDK's msgpack decoder, but
 *  this client decodes without `useBigInt64`, so the same fields land as
 *  plain `number`. */
type Jsonify<T> = T extends bigint ? number
  : T extends object ? { [K in keyof T]: Jsonify<T[K]> }
  : T;

type Assert<T extends true> = T;

/** Server → client frames the page consumes. */
type InboundKind =
  | 'register_ack'
  | 'subscribe_state'
  | 'gap'
  | 'message'
  | 'messages'
  | 'answer_delta'
  | 'reasoning'
  | 'tool_started'
  | 'tool_completed'
  | 'status'
  | 'task_list'
  | 'turn_state'
  | 'notice'
  | 'approval_requested'
  | 'approval_resolved'
  | 'history_append'
  | 'history_snapshot'
  | 'bot_status'
  | 'slash_manifest'
  | 'folders_changed'
  | 'session_updated'
  | 'session_activity'
  // deck frames — no deck UI here; the native deck shell consumes them
  // board invalidations — the projects pages consume them
  | 'project_changed'
  | 'deck_card_data'
  | 'deck_changed'
  | 'ping'
  | 'pong';

/** Client → server frames the page encodes. */
type OutboundKind =
  | 'register'
  | 'subscribe'
  | 'unsubscribe'
  | 'message'
  | 'messages'
  | 'resolve_approval'
  | 'start_bot'
  | 'stop_bot'
  | 'ping'
  | 'pong';

// A renamed/removed wire variant first collapses `Extract` to `never` — which
// extends anything — so existence is asserted separately (non-distributive).
export type MirroredKindsExist = Assert<
  [InboundKind | OutboundKind] extends [GeneratedFrame['kind']] ? true : false
>;

/** Inbound kinds whose generated shape is no longer assignable to the
 *  hand-written mirror. Inspect this type when the assert fires. */
type InboundDrift = {
  [K in InboundKind]: Jsonify<Extract<GeneratedFrame, { kind: K }>> extends Extract<Frame, { kind: K }>
    ? never
    : K;
}[InboundKind];

/** Outbound kinds whose hand-written mirror no longer satisfies the shape the
 *  server decodes. */
type OutboundDrift = {
  [K in OutboundKind]: Extract<Frame, { kind: K }> extends Jsonify<Extract<GeneratedFrame, { kind: K }>>
    ? never
    : K;
}[OutboundKind];

export type InboundContractHolds = Assert<[InboundDrift] extends [never] ? true : false>;
export type OutboundContractHolds = Assert<[OutboundDrift] extends [never] ? true : false>;

/** Assignability alone misses two drift classes: a wire-side REMOVAL of a
 *  field the mirror declares optional (inbound reads silently become
 *  `undefined`), and a dead field the client still encodes (excess properties
 *  are ignored in type-to-type checks; the server silently drops it — e.g. a
 *  renamed `platform_msg_id` would break send dedup with no error anywhere).
 *  So additionally: every key the hand-written mirror declares, in either
 *  direction, must still exist on the generated shape. */
type DroppedKeys = {
  [K in InboundKind | OutboundKind]: Exclude<
    keyof Extract<Frame, { kind: K }>,
    keyof Jsonify<Extract<GeneratedFrame, { kind: K }>>
  > extends never
    ? never
    : K;
}[InboundKind | OutboundKind];
export type NoMirroredFieldDropped = Assert<[DroppedKeys] extends [never] ? true : false>;

// The nested row/attachment shapes ride inside `message` / `messages` frames.
export type NoMessageFieldDropped = Assert<
  [Exclude<keyof WireMessage, keyof Jsonify<Message>>] extends [never] ? true : false
>;
export type NoAttachmentFieldDropped = Assert<
  [Exclude<keyof WireAttachment, keyof GeneratedAttachment>] extends [never] ? true : false
>;

// Negative controls: deliberately drifted shapes must FAIL the same checks,
// guarding the sentinel against ever becoming vacuously true.
type PoisonedReasoning = { kind: 'reasoning'; text: number };
// @ts-expect-error — generated `text: string` must not satisfy `text: number`
export type NegativeControl = Assert<[Jsonify<Extract<GeneratedFrame, { kind: 'reasoning' }>>] extends [PoisonedReasoning] ? true : false>;
type PoisonedExtraField = { kind: 'reasoning'; text: string; bogus?: string };
// @ts-expect-error — a hand-declared field absent from the wire contract must be caught
export type NegativeControlKeys = Assert<[Exclude<keyof PoisonedExtraField, keyof Jsonify<Extract<GeneratedFrame, { kind: 'reasoning' }>>>] extends [never] ? true : false>;
