[package]
name = "baybo-mobile-core"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
wire = { workspace = true }
device-proto = { workspace = true }
baybo-model = { workspace = true }
thiserror = { workspace = true }
snow = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
