use aura_model::ChannelType;
use serde::{Deserialize, Serialize};

use super::error::SdkError;

/// Wire-format version this SDK speaks. Bump on breaking frame changes.
pub const PROTOCOL_VERSION: u16 = 1;

/// The canonical sidecar-to-aura (or aura-to-sidecar) message. A single
/// SDK connection may carry messages for many `user_id`s — the sidecar
/// multiplexes its users onto one WebSocket.
///
/// `channel_type` holds an [`aura_model::ChannelType`] but exports to
/// TypeScript as a plain `string` — the domain type is a transparent
/// newtype over `String`, and we don't want ts-rs to pull the domain
/// crate into its generated schema.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../sdks/channel-ts/src/generated/")
)]
pub struct Message {
    pub content: String,
    pub session_id: String,
    pub user_id: String,
    #[cfg_attr(feature = "ts-export", ts(type = "string"))]
    pub channel_type: ChannelType,
}

/// Frame envelope. Tagged on the `kind` field so the receive side
/// never has to guess. Encoded with
/// [`rmp_serde::to_vec_named`](rmp_serde::to_vec_named) so field names
/// round-trip — makes it trivial to hand-write a TypeScript decoder.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[cfg_attr(feature = "ts-export", derive(ts_rs::TS))]
#[cfg_attr(
    feature = "ts-export",
    ts(export, export_to = "../../../sdks/channel-ts/src/generated/")
)]
pub enum Frame {
    /// First frame after the WebSocket handshake. Carries the
    /// sidecar's capability token (injected via `AURA_CHANNEL_TOKEN`)
    /// and its declared channel type.
    Register {
        token: String,
        #[cfg_attr(feature = "ts-export", ts(type = "string"))]
        channel_type: ChannelType,
        protocol_version: u16,
    },
    /// Server response to `Register`. `ok: false` carries a
    /// human-readable reason; the SDK surfaces it as
    /// [`SdkError::RegistrationRejected`](super::error::SdkError::RegistrationRejected).
    RegisterAck { ok: bool, reason: Option<String> },
    /// A user-visible message flowing in either direction.
    Message(Message),
}

/// Serialize a frame with named fields (MessagePack map representation).
pub fn encode(frame: &Frame) -> Result<Vec<u8>, SdkError> {
    rmp_serde::to_vec_named(frame).map_err(SdkError::from)
}

/// Deserialize a frame.
pub fn decode(bytes: &[u8]) -> Result<Frame, SdkError> {
    rmp_serde::from_slice(bytes).map_err(SdkError::from)
}

/// Regenerates `sdks/channel-ts/src/generated/constants.ts` with
/// Rust-authored values so the TS SDK doesn't keep its own copy of
/// `PROTOCOL_VERSION` (and any future wire-level constants).
/// Pairs with the `ts-rs`-driven type exports above; both run under
/// the same `ts-export` feature gate and land in the same directory.
#[cfg(all(test, feature = "ts-export"))]
#[test]
fn export_constants() {
    let out = format!(
        "// This file was generated by aura-channels. Do not edit this file manually.\n\
         export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    );
    std::fs::write("../../sdks/channel-ts/src/generated/constants.ts", out)
        .expect("write generated constants.ts");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_register() {
        let frame = Frame::Register {
            token: "deadbeef".into(),
            channel_type: ChannelType::from("slack"),
            protocol_version: PROTOCOL_VERSION,
        };
        let bytes = encode(&frame).unwrap();
        let back = decode(&bytes).unwrap();
        assert_eq!(frame, back);
    }

    #[test]
    fn round_trip_message() {
        let frame = Frame::Message(Message {
            content: "hi".into(),
            session_id: "s1".into(),
            user_id: "u1".into(),
            channel_type: ChannelType::from("slack"),
        });
        let bytes = encode(&frame).unwrap();
        assert_eq!(frame, decode(&bytes).unwrap());
    }

    #[test]
    fn round_trip_ack_rejected() {
        let frame = Frame::RegisterAck {
            ok: false,
            reason: Some("bad token".into()),
        };
        assert_eq!(frame, decode(&encode(&frame).unwrap()).unwrap());
    }
}
