[package]
name = "baybo-janitor"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
async-trait = { workspace = true }
baybo-store = { workspace = true }
baybo-workspace = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
parking_lot = { workspace = true }
baybo-model = { workspace = true }
baybo-workspace = { workspace = true, features = ["test-support"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "fs"] }
