import { spawn, spawnSync } from "node:child_process";
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

const IOS_BUNDLE_IDS = ["com.baybo.app", "com.baybo.app.NotificationExtension"];
const MOBILE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const APPLE_DIR = join(MOBILE_DIR, "src-tauri", "gen", "apple");

const args = process.argv.slice(2);
const env = { ...process.env };

if (args[0] === "ios") {
  const team = firstNonEmpty(
    env.BAYBO_IOS_DEVELOPMENT_TEAM,
    env.DEVELOPMENT_TEAM,
    env.BAYBO_TEAM_ID,
    inferTeamFromProvisioningProfiles(),
  );

  if (team) {
    env.BAYBO_IOS_DEVELOPMENT_TEAM = team;
    writeLocalSigningConfig(team);
    if (!process.env.BAYBO_IOS_DEVELOPMENT_TEAM) {
      console.error(`baybo-mobile: using iOS development team ${team}`);
    }
  } else {
    console.error(
      "baybo-mobile: missing iOS development team. Set BAYBO_IOS_DEVELOPMENT_TEAM, " +
        "or open the project in Xcode once so automatic signing creates a provisioning profile.",
    );
    process.exit(1);
  }
}

const child = spawn("tauri", args, { stdio: "inherit", env });

child.on("exit", (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }
  process.exit(code ?? 1);
});

child.on("error", (error) => {
  console.error(`baybo-mobile: failed to run tauri: ${error.message}`);
  process.exit(1);
});

function firstNonEmpty(...values) {
  return values.find((value) => typeof value === "string" && value.trim() !== "")?.trim();
}

function inferTeamFromProvisioningProfiles() {
  const dir = join(homedir(), "Library/Developer/Xcode/UserData/Provisioning Profiles");
  if (!existsSync(dir)) {
    return undefined;
  }

  const candidates = [];
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith(".mobileprovision")) {
      continue;
    }
    const xml = decodeProvisioningProfile(join(dir, entry));
    if (!xml) {
      continue;
    }
    const team = extractTeamId(xml);
    const score = profileScore(xml);
    if (team && score !== undefined) {
      candidates.push({ team, score });
    }
  }

  candidates.sort((a, b) => a.score - b.score);
  return candidates[0]?.team;
}

function decodeProvisioningProfile(path) {
  const result = spawnSync("security", ["cms", "-D", "-i", path], {
    encoding: "utf8",
    maxBuffer: 1024 * 1024 * 4,
  });
  if (result.status !== 0) {
    return undefined;
  }
  return result.stdout;
}

function extractTeamId(xml) {
  return (
    extractArrayValue(xml, "ApplicationIdentifierPrefix") ?? extractArrayValue(xml, "TeamIdentifier")
  );
}

function profileScore(xml) {
  const appIds = [...xml.matchAll(/<key>application-identifier<\/key>\s*<string>([^<]+)<\/string>/g)]
    .map((match) => match[1]);

  for (const [index, bundleId] of IOS_BUNDLE_IDS.entries()) {
    if (appIds.some((appId) => appId.endsWith(`.${bundleId}`))) {
      return index;
    }
  }

  if (appIds.some((appId) => appId.endsWith(".*"))) {
    return IOS_BUNDLE_IDS.length;
  }

  return undefined;
}

function extractArrayValue(xml, key) {
  const pattern = new RegExp(`<key>${key}</key>\\s*<array>\\s*<string>([^<]+)</string>`);
  return xml.match(pattern)?.[1];
}

function writeLocalSigningConfig(team) {
  if (!/^[A-Z0-9]+$/.test(team)) {
    console.error(`baybo-mobile: invalid iOS development team '${team}'`);
    process.exit(1);
  }

  writeFileSync(
    join(APPLE_DIR, "Signing.local.xcconfig"),
    [
      "// Generated by app/mobile/scripts/tauri-env.mjs. Do not commit.",
      `BAYBO_IOS_DEVELOPMENT_TEAM = ${team}`,
      "",
    ].join("\n"),
  );
}
