[package]
name = "baybo-pairing"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
baybo-model = { workspace = true }
baybo-store = { workspace = true }

chrono = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
