// Compile-time drift sentinel — type-only, produces no runtime output.
//
// The transcript's hand-written `WireFrame` deliberately models only the
// subset of wire frames it renders (plus native-synthesized `history_page`,
// `catch_up`, and `history_failed`), tolerant of everything else. The authoritative TS
// contract is generated by ts-rs from `crates/wire` — the same crate the ffi
// pump serializes — into `sidecars/sdk/channel-ts/src/generated/`, CI-gated
// by `scripts/check-ts-bindings.sh`. This file asserts that, for every kind
// the transcript mirrors, the generated (runtime-true) shape stays assignable
// to the hand-written one, so a wire-side rename/retype fails `pnpm build`
// here instead of silently dropping frames at runtime.
import type { Frame } from "../../../../sidecars/sdk/channel-ts/src/generated/Frame";
import type { Message } from "../../../../sidecars/sdk/channel-ts/src/generated/Message";
import type { WireAttachment as GeneratedAttachment } from "../../../../sidecars/sdk/channel-ts/src/generated/WireAttachment";
import type { WireAttachment, WireFrame, WireMessage } from "./types";

/// ts-rs maps u64/i64 to `bigint` — correct for the SDK's msgpack decoder,
/// but this bundle receives frames as `serde_json` text → `JSON.parse`, where
/// the same fields land as plain `number`.
type Jsonify<T> = T extends bigint ? number
  : T extends object ? { [K in keyof T]: Jsonify<T[K]> }
  : T;

type Assert<T extends true> = T;

/// Every `WireFrame` kind that mirrors a real wire frame (`history_page`,
/// `catch_up`, `history_failed`, and the tolerance catch-all `other` are
/// transcript-local).
type MirroredKind =
  | "message"
  | "attachment"
  | "answer_delta"
  | "reasoning"
  | "tool_started"
  | "tool_completed"
  | "turn_state"
  | "work_snapshot"
  | "notice"
  | "reset";

// A renamed/removed wire variant first collapses `Extract` to `never` — which
// extends anything — so existence is asserted separately (non-distributive).
export type MirroredKindsExist = Assert<
  [MirroredKind] extends [Frame["kind"]] ? true : false
>;

/// Kinds whose generated shape is NOT assignable to the hand-written one.
/// Inspect this type when the assertion below fires — it names the drift.
type Drifted = {
  [K in MirroredKind]: Jsonify<Extract<Frame, { kind: K }>> extends Extract<WireFrame, { kind: K }>
    ? never
    : K;
}[MirroredKind];

export type WireContractHolds = Assert<[Drifted] extends [never] ? true : false>;

/// Assignability alone is blind to a wire-side REMOVAL of a field the mirror
/// declares optional (a missing optional is compatible), which would silently
/// turn every read of it into `undefined`. So additionally: every key the
/// hand-written mirror declares must still exist on the generated shape.
type DroppedKeys = {
  [K in MirroredKind]: Exclude<
    keyof Extract<WireFrame, { kind: K }>,
    keyof Jsonify<Extract<Frame, { kind: K }>>
  > extends never
    ? never
    : K;
}[MirroredKind];
export type NoMirroredFieldDropped = Assert<[DroppedKeys] extends [never] ? true : false>;

// The nested row/attachment shapes ride inside live `message` frames and native
// history API pages — their keys need the same existence guarantee.
export type NoMessageFieldDropped = Assert<
  [Exclude<keyof WireMessage, keyof Jsonify<Message>>] extends [never] ? true : false
>;
export type NoAttachmentFieldDropped = Assert<
  [Exclude<keyof WireAttachment, keyof GeneratedAttachment>] extends [never] ? true : false
>;

// Negative controls: deliberately drifted shapes must FAIL the same checks,
// guarding the sentinel against ever becoming vacuously true.
type PoisonedReasoning = { kind: "reasoning"; text: number };
// @ts-expect-error — generated `text: string` must not satisfy `text: number`
export type NegativeControl = Assert<[Jsonify<Extract<Frame, { kind: "reasoning" }>>] extends [PoisonedReasoning] ? true : false>;
type PoisonedExtraField = { kind: "reasoning"; text: string; bogus?: string };
// @ts-expect-error — a hand-declared field absent from the wire contract must be caught
export type NegativeControlKeys = Assert<[Exclude<keyof PoisonedExtraField, keyof Jsonify<Extract<Frame, { kind: "reasoning" }>>>] extends [never] ? true : false>;
