//! Generates each provider's flat-default pricing from the bundled
//! OpenRouter snapshot (`src/providers/openrouter_pricings.json`) at
//! build time.
//!
//! `flat_default_pricing` is the full pricing row of the model with the
//! highest `input + output` per-1M rate among the snapshot slugs under
//! the provider's OpenRouter prefix — the conservative unknown-id
//! fallback for the budget gate.
//!
//! A provider whose prefix matches zero priced snapshot models fails the
//! build: the bundled snapshot is missing or was regenerated wrong, and
//! shipping no fallback rate would silently disable cost attribution.
//! This is the "report a compile error if it isn't there" guarantee.
//!
//! Pricing strings are per-token USD; the micros conversion mirrors
//! `baybo_llm::openrouter` / `MicroUsd::from_usd_decimal` step-for-step
//! (`round((v * 1e6) * 1e6)`, saturating) so a generated flat default is
//! bit-identical to the runtime snapshot pricing for the same model.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

// Pull in the shared `(provider, prefix)` table without duplicating it.
// The fn in there is unused on the build side (we iterate the array
// directly), hence the allow.
#[allow(dead_code)]
mod prefix {
    include!("src/providers/openrouter_prefix.rs");
}

const SNAPSHOT_PATH: &str = "src/providers/openrouter_pricings.json";

/// One model's per-1M micro-USD rates, all four `ModelPricing` fields.
type PricingRow = (i64, i64, Option<i64>, Option<i64>);

fn main() {
    println!("cargo:rerun-if-changed={SNAPSHOT_PATH}");
    println!("cargo:rerun-if-changed=src/providers/openrouter_prefix.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let raw =
        fs::read_to_string(SNAPSHOT_PATH).unwrap_or_else(|e| panic!("read {SNAPSHOT_PATH}: {e}"));
    let json: serde_json::Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("parse {SNAPSHOT_PATH}: {e}"));
    let models = json
        .get("models")
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("{SNAPSHOT_PATH}: missing `models` object"));

    let mut out = String::new();
    out.push_str("// @generated by build.rs from openrouter_pricings.json — do not edit.\n\n");

    for &(provider, or_prefix) in prefix::OPENROUTER_PROVIDER_PREFIXES {
        // BTreeMap keeps both the generated list and the tie-break
        // deterministic (lexicographic) regardless of JSON key order.
        let mut priced: BTreeMap<String, PricingRow> = BTreeMap::new();
        let want = format!("{or_prefix}/");
        for (slug, entry) in models {
            let Some(id) = slug.strip_prefix(&want) else {
                continue;
            };
            // Mirror the runtime snapshot filter: a row missing/garbled
            // prompt or completion is dropped, not defaulted to zero.
            let (Some(prompt), Some(completion)) = (
                pricing_field(entry, "prompt"),
                pricing_field(entry, "completion"),
            ) else {
                continue;
            };
            let (Some(input), Some(output)) =
                (per_token_micros(prompt), per_token_micros(completion))
            else {
                continue;
            };
            priced.insert(
                id.to_string(),
                (
                    input,
                    output,
                    pricing_field(entry, "input_cache_read").and_then(per_token_micros),
                    pricing_field(entry, "input_cache_write").and_then(per_token_micros),
                ),
            );
        }

        if priced.is_empty() {
            panic!(
                "openrouter snapshot has no priced models under `{or_prefix}/` for provider \
                 `{provider}`. The bundled {SNAPSHOT_PATH} is missing or was regenerated wrong — \
                 run scripts/regen-openrouter-pricings.sh."
            );
        }

        // Priciest by input+output, ties broken to the lexicographically
        // smallest slug (the `.then(b_id.cmp(a_id))` flips id order so the
        // smaller id reads as "greater") — fully deterministic across builds.
        let (best_id, best) = priced
            .iter()
            .max_by(|(a_id, a), (b_id, b)| (a.0 + a.1).cmp(&(b.0 + b.1)).then(b_id.cmp(a_id)))
            .map(|(id, row)| (id.clone(), *row))
            .unwrap_or_else(|| unreachable!("priced is non-empty"));

        let upper = provider.to_ascii_uppercase().replace('-', "_");

        writeln!(
            out,
            "// flat default = priciest by input+output: {or_prefix}/{best_id}"
        )
        .unwrap();
        writeln!(
            out,
            "pub(crate) const {upper}_FLAT_DEFAULT_PRICING: ModelPricing = ModelPricing {{"
        )
        .unwrap();
        writeln!(
            out,
            "    input_per_1m_tokens: MicroUsd::from_micros({}),",
            best.0
        )
        .unwrap();
        writeln!(
            out,
            "    output_per_1m_tokens: MicroUsd::from_micros({}),",
            best.1
        )
        .unwrap();
        writeln!(
            out,
            "    cached_input_per_1m_tokens: {},",
            opt_micros(best.2)
        )
        .unwrap();
        writeln!(
            out,
            "    cache_write_per_1m_tokens: {},",
            opt_micros(best.3)
        )
        .unwrap();
        out.push_str("};\n\n");
    }

    let dest =
        Path::new(&env::var("OUT_DIR").expect("OUT_DIR set by cargo")).join("provider_catalog.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// `models[slug].pricing.<name>` as a string, if present. The snapshot
/// stores every rate as a per-token USD string.
fn pricing_field<'a>(entry: &'a serde_json::Value, name: &str) -> Option<&'a str> {
    entry.get("pricing")?.get(name)?.as_str()
}

/// Per-token USD string -> micro-USD per 1M tokens, matching
/// `baybo_llm::openrouter::parse_per_token_to_per_million_micros` composed
/// with `MicroUsd::from_usd_decimal` step-for-step. `None` for non-finite,
/// negative, or unparseable input so build-time filtering mirrors the
/// runtime snapshot filter exactly.
fn per_token_micros(s: &str) -> Option<i64> {
    let v: f64 = s.parse().ok()?;
    if !v.is_finite() || v < 0.0 {
        return None;
    }
    // Two-step on purpose: the runtime computes `v * 1e6` first, then
    // `from_usd_decimal` multiplies that by 1e6 and rounds. Fusing to
    // `v * 1e12` could differ by an ULP — keep the same float order.
    let per_million_usd = v * 1_000_000.0;
    let scaled = (per_million_usd * 1_000_000.0).round();
    Some(if scaled >= i64::MAX as f64 {
        i64::MAX
    } else if scaled <= i64::MIN as f64 {
        i64::MIN
    } else {
        scaled as i64
    })
}

fn opt_micros(v: Option<i64>) -> String {
    match v {
        Some(m) => format!("Some(MicroUsd::from_micros({m}))"),
        None => "None".to_string(),
    }
}
